vmware-clarity/ng-clarity

README.md
docs/CONTRIBUTING_DESIGN.md
docs/CONTRIBUTING_DEVELOPMENT.md
docs/CONTRIBUTING_DOCUMENTATION.md
projects/angular/package.json
projects/ui/package.json

This reverts some of the changes from: https://github.com/vmware/clarity/pull/6731/ now that there's no special branch for angular and updates url

chore: update branch name and urls

---

projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/datagrid-column-toggle.ts

fix: the show columns dialog contains an implicit heading vpat-795

---

projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/datagrid-column-toggle.ts

fix: the show columns dialog contains an implicit heading vpat-795 (backport)

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/contribution-proposal.md
.github/pull_request_template.md

chore: add issue and PR templates

---

package.json

chore(build): fix build:angular:watch script

---

projects/angular/src/data/tree-view/tree-node.ts

Signed-off-by: Scott Mathis <smathis@vmware.com>
Fixes what happens on an open parent tree node when the enter or spacebar is pressed.
Also adds some preventDefaults to prevent the page from scrolling unexpectedly when home/end keys are pressed.
See notes on vpat-684

fix(tree-view): fix enter/space key interaction with open parent tree nodes

---

docs/CONTRIBUTING_DEVELOPMENT.md
package-lock.json
package.json

chore: update running steps for development in the contribution docs

---

projects/angular/src/popover/dropdown/_dropdown.clarity.scss

(Backport) fix(dropdown): icon trigger alignment with label

---

.github/workflows/build.yml
.github/workflows/preview.yml
.github/workflows/release.yml

chore: add npx to netlify deploy workflow commands

---

.github/workflows/build.yml
.github/workflows/demo.yml

This fixes the problem of demos not being deployed when on forked branches

deploy forked demos

---

.github/workflows/build.yml
.github/workflows/demo.yml

This fixes the problem of demos not being deployed when on forked branches

deploy forked demos (12.x)

---

.github/workflows/label-stale-threads.yml
.github/workflows/lock-inactive-threads.yml

add stale and inactive threads workflows

chore: add stale and inactive threads workflows

---

.github/workflows/demo.yml

This will cause the demo action to fail if the demo fails to deploy

chore: report failure if demo fails to upload

---

projects/angular/src/wizard/providers/wizard-navigation.service.spec.ts
projects/angular/src/wizard/providers/wizard-navigation.service.ts
projects/angular/src/wizard/wizard.spec.ts
projects/angular/src/wizard/wizard.ts

backport of https://github.com/vmware/clarity/pull/6670

(backport) fix(wizard): move wizard focus after page change

---

projects/angular/src/layout/nav/nav-level.spec.ts
projects/angular/src/layout/nav/nav-level.ts

Screen reader reads the navigation elements even they are hidden
Screen reader doesn't read the navigation hidden items

fix(navigation): add aria-hidden attributes to hidden elements

---

projects/angular/clarity.api.md
projects/angular/src/layout/nav/_responsive-nav.clarity.scss
projects/angular/src/layout/nav/header.ts
projects/angular/src/layout/nav/nav-level.spec.ts
projects/angular/src/layout/nav/nav-level.ts
projects/angular/src/utils/breakpoints/breakpoints.ts
projects/angular/src/utils/focus-trap/focus-trap.spec.ts
projects/angular/src/utils/focus-trap/focus-trap.ts
projects/angular/src/utils/i18n/common-strings.default.ts
projects/angular/src/utils/i18n/common-strings.interface.ts

(Backport) fix(navigation): a11y focus trap in responsive mode

---

projects/angular/src/forms/datepicker/calendar.html

fix: datepicker 'days' row is not set as table header (backport)

---

package.json
projects/angular/clarity.api.md

fix ci npm publish step due to demo build modifying dist with ngcc

chore: fix ci publishing (v12)

---

projects/angular/src/layout/nav/nav-level.ts

fix(navigation): visibility of navigation section when clicking on nav-link

---

projects/angular/src/layout/nav/nav-level.ts

(backport) fix(navigation): visibility of navigation when nav-link is clicked

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/datagrid-placeholder.ts
projects/angular/src/data/datagrid/datagrid.html
projects/angular/src/data/datagrid/datagrid.spec.ts
projects/angular/src/data/datagrid/datagrid.ts
projects/angular/src/data/datagrid/helpers.spec.ts
projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts

Key focus navigation added to datagrid

feat: enable key navigation for datagrid

---

projects/angular/src/layout/nav/_responsive-nav.clarity.scss
projects/angular/src/layout/nav/nav-level.ts

fix(navigation): visibility of close button in tablet and mobile view

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/datagrid-placeholder.ts
projects/angular/src/data/datagrid/datagrid.html
projects/angular/src/data/datagrid/datagrid.spec.ts
projects/angular/src/data/datagrid/datagrid.ts
projects/angular/src/data/datagrid/helpers.spec.ts
projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts

feat: enable key navigation for datagrid (backport)

---

package-lock.json
projects/angular/src/utils/variables/_variables.global.scss
projects/demo/src/app/app.routing.ts
projects/demo/src/app/z-index/custom-filter.demo.ts
projects/demo/src/app/z-index/various-content/various-content.html
projects/demo/src/app/z-index/various-content/various-content.ts
projects/demo/src/app/z-index/z-index.demo.html
projects/demo/src/app/z-index/z-index.demo.module.ts
projects/demo/src/app/z-index/z-index.demo.ts
projects/demo/src/app/z-index/z-index.routing.ts

fix: fix multiple overlay nesting scenarios (backport)

---

package-lock.json
package.json
projects/demo/src/app/app.component.html
projects/demo/src/app/app.component.ts
projects/demo/src/app/content-container.component.ts
projects/demo/src/styles.scss

switch sidenav to vertical nav

chore: update demo app to use shim

---

projects/demo/src/app/app.component.html
projects/demo/src/app/app.component.ts
projects/demo/src/app/app.module.ts
projects/demo/src/app/cds-theme-path-location-strategy.ts
projects/demo/src/app/cds-theme-select.component.ts

chore: add cds theme to query string in demo app

---

package.json

chore: update `prepare` script to work on windows

---

package-lock.json
package.json

I'm mostly doing this to get a demo environment to show colin of the shim changes

chore: update clarity core version

---

projects/angular/src/forms/combobox/_combobox.clarity.scss
projects/angular/src/forms/combobox/options.ts
projects/angular/src/forms/combobox/providers/combobox-focus-handler.service.ts

fix(combobox): keep focus while filtering and improve input .. back port

---

projects/demo/src/app/spinners/spinner-component.html

chore: remove references to non-existent `clrOff` and `clrAssertive` spinner inputs

---

projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts

This is a backport of vmware/clarity#6657 and prep for backporting #70.
Issue Number: https://jira.eng.vmware.com/browse/VPAT-687

feat: add placeholder to datagrid string filter (v12 backport)

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.spec.ts
projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.ts
projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
projects/angular/src/data/datagrid/datagrid-column.ts

fix: provide a way to change placeholder and aria-label for builtin filters (v12 backport)

---

projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/stack-view/_stack-view.clarity.scss
projects/demo/src/app/app.routing.ts
projects/demo/src/app/overlay-clipping/overlay-clipping.demo.html
projects/demo/src/app/overlay-clipping/overlay-clipping.demo.module.ts
projects/demo/src/app/overlay-clipping/overlay-clipping.demo.ts
projects/demo/src/app/overlay-clipping/overlay-clipping.routing.ts

fix: overlay clipping issues (backport)

---

projects/angular/clarity.api.md
projects/angular/src/popover/tooltip/tooltip-content.ts
projects/angular/src/utils/assert/assert.helpers.ts

chore(tooltip): various code cleanup/refactoring

---

.github/workflows/label-stale-threads.yml
.github/workflows/lock-inactive-threads.yml
.github/workflows/pr-build.yml
.github/workflows/pr-comment-bot.yml
.github/workflows/pr-preview.yml
.github/workflows/preview.yml
.github/workflows/release-preview.yml

I think these workflows name are more descriptive/reflective of what the workflows do.

chore: rename workflows for descriptiveness

---

package-lock.json
package.json

This was added in 5c83e453eb259f0945f2226867c1f854526653ca but is not used or needed.
Build changes

chore: remove unused `@angular/cdk` dependency

---

.storybook/stories/datagrid/datagrid-action-overflow.stories.ts
.storybook/stories/datagrid/datagrid-column.stories.ts
.storybook/stories/datagrid/datagrid-detail.stories.ts
.storybook/stories/datagrid/datagrid-page-size.stories.ts
.storybook/stories/datagrid/datagrid-pagination.stories.ts
.storybook/stories/datagrid/datagrid-placeholder.stories.ts
.storybook/stories/datagrid/datagrid-row.stories.ts
.storybook/stories/datagrid/datagrid.stories.ts

chore: add datagrid stories

---

.storybook/stories/stack-view/stack-block.stories.ts
.storybook/stories/stack-view/stack-view-with-lazy-loaded-blocks.stories.ts
.storybook/stories/stack-view/stack-view.stories.ts

I did not document inline editing as that feature appears to be experimental.
Storybook

chore: add stack view stories

---

.storybook/helpers/files.data.ts
.storybook/stories/tree/tree-node.stories.ts
.storybook/stories/tree/tree-with-lazy-loaded-nodes.stories.ts
.storybook/stories/tree/tree-with-lazy-loaded-recursive-nodes.stories.ts
.storybook/stories/tree/tree-with-recursive-nodes.stories.ts
.storybook/stories/tree/tree.stories.ts

Co-Authored-By: Bogdan Bogdanov <bbogdanov@vmware.com>
storybook

chore: add tree stories

---

.github/workflows/pr-visual-regression.yml
.github/workflows/release.yml
.storybook/helpers/setup-storybook.helpers.ts
.storybook/preview.js

chore: add chromatic support

---

.storybook/stories/forms/forms.stories.ts
.storybook/stories/header/header.stories.ts
.storybook/stories/label/label.stories.ts

add forms and labels stories

---

.github/workflows/pr-build.yml
.github/workflows/pr-preview.yml
.github/workflows/pr-visual-regression.yml
.github/workflows/release-preview.yml
.github/workflows/release.yml
angular.json
netlify.toml
package.json

- The `main` branch has storybook and the `12.x` branch does not, so the preview deployment fails for backports.
- The artifact is downloaded from the most recent successful PR Build workflow run.
- With this rename, the `main` and `12.x` branches can use the same path and artifact name for the docs.
- The artifact is downloaded from the specific PR Build workflow run that triggered the deployment workflow.
No

chore: various fixes for deployment workflows

---

.github/workflows/pr-visual-regression.yml

chore: report correct sha and branch name to chromatic

---

.storybook/stories/datagrid/datagrid-action-overflow.stories.ts
.storybook/stories/datagrid/datagrid-column.stories.ts
.storybook/stories/datagrid/datagrid-detail.stories.ts
.storybook/stories/datagrid/datagrid-page-size.stories.ts
.storybook/stories/datagrid/datagrid-pagination.stories.ts
.storybook/stories/datagrid/datagrid-placeholder.stories.ts
.storybook/stories/datagrid/datagrid-row.stories.ts
.storybook/stories/datagrid/datagrid.stories.ts

chore: set explicit column widths in datagrid stories

---

.github/workflows/pr-visual-regression.yml

chore: pass repo to chromatic so baseline can be found for forks

---

.github/workflows/pr-visual-regression.yml

Since `12.x` doesn't have Storybook, the Chromatic tests won't work.

chore: skip chromatic tests for changes that do not target `main`

---

docs/CONTRIBUTING_DEVELOPMENT.md

Just started with another PR and saw that there is a small error in the `docs/CONTRIBUTING_DEVELOPMENT.md` file.

chore: contributing docs "npm build" does not work

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid-row.html
projects/angular/src/data/datagrid/datagrid-row.ts
projects/angular/src/data/datagrid/datagrid.spec.ts
projects/angular/src/data/datagrid/datagrid.ts
projects/angular/src/data/datagrid/providers/selection.ts

feat(datagrid): range selection with shift key (v12 back port)

---

.github/workflows/pr-build.yml
projects/angular/package.json
scripts/clear-npm-script.js

This will prevent us from merging code that requires @cds/core@6  like we did in #134.

chore: build with each allowed major version of @cds/core

---

projects/angular/package.json

Signed-off-by: Matthew Hippely <hippely@gmail.com>
To use @clr/angular with @angular/*@14 it currently requires an `npm i --force` which is not ideal. 
This came up when upgrading an application to latest angular versions because of a finding during a security review. 

feat: widen angular peer deps

---

projects/angular/src/wizard/_wizard.clarity.scss

fixes #107
backport of #251
There's a weird vertical scroll bar in the wizard on a div that is way too tall
Issue Number: #107
use flex-grow to make the div take up the full height instead of the previous attempted fix min-height 70vh

fix(wizard): remove unnecessary vertical scroll bar (backport)

---

projects/angular/src/forms/datepicker/day.spec.ts
projects/angular/src/forms/datepicker/day.ts

Feature
The `aria-current` attribute is not present on the button for the current day.
The `aria-current` attribute is present on the button for the current day.
No.

feat(datepicker): indicate current day with aria-current

---

docs/CONTRIBUTING_DEVELOPMENT.md
docs/CONTRIBUTING_DEV_BUG_FIXES.md
docs/CONTRIBUTING_DEV_FEATURES.md

The contribution docs are now divided in 3 smaller documents
- landing page, containing links to bug-fix docs and feature docs; also contains the Prerequisites and Getting Started.
- bug-fix, small-feature docs, contains information on creating fork, preparing commits, submitting PR
- component/big-feature/refactoring docs, which add Proposal Template and instruction to working in a topic-branch to the smaller previous scenario
Preview changes here: https://github.com/Jinnie/ng-clarity/blob/main/docs/CONTRIBUTING_DEVELOPMENT.md

chore: improve dev contribution documentation

---

.storybook/stories/forms/forms.stories.ts

Add `clr-control-success` to the forms story

chore: add clr-control-success to forms story

---

.storybook/stories/datagrid/datagrid-row.stories.ts

chore(datagrid): add a11y inputs handling for the row in storybook

---

.github/workflows/pr-visual-regression.yml

We don't need to wait for the test results in the visual regression workflow b/c Chromatic will report the results separately.

chore: exit once story upload is complete

---

.storybook/stories/button/button.stories.ts

Add button variations to the button story

chore: add button variations to button story

---

projects/angular/src/forms/styles/_properties.forms.scss
projects/angular/src/forms/styles/_radio.clarity.scss

fixes #258
Bugfix
Issue Number: #258
The disabled radio buttons look correct.
No

fix(radio): use correct styles for disabled radio buttons

---

projects/angular/src/forms/styles/_properties.forms.scss
projects/angular/src/forms/styles/_radio.clarity.scss

fixes #258
This is a backport of #284.
Bugfix
Issue Number: #258
The disabled radio buttons look correct.
No

fix(radio): use correct styles for disabled radio buttons (v12 backport)

---

README.md

chore(docs): fix install links in readme

---

README.md

chore(docs): fix install links in readme (v12 backport)

---

projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss

closes #293
Bugfix
Issue Number: #293
The icon and text does shift when a link is selected.
No

fix(vertical-nav): align icon and text of selected link with other links

---

projects/angular/src/forms/checkbox/checkbox-container.ts
projects/angular/src/forms/combobox/combobox-container.ts
projects/angular/src/forms/common/control-container.ts
projects/angular/src/forms/datalist/datalist-container.ts
projects/angular/src/forms/datepicker/date-container.ts
projects/angular/src/forms/input/input-container.ts
projects/angular/src/forms/password/password-container.ts
projects/angular/src/forms/radio/radio-container.ts
projects/angular/src/forms/range/range-container.ts
projects/angular/src/forms/select/select-container.ts
projects/angular/src/forms/styles/_containers.clarity.scss
projects/angular/src/forms/styles/containers.spec.ts
projects/angular/src/forms/textarea/textarea-container.ts
projects/demo/src/app/checkboxes/checkboxes.demo.html
projects/demo/src/app/forms/controls/checkbox.html
projects/demo/src/app/forms/controls/file.html
projects/demo/src/app/forms/controls/radio.html
projects/demo/src/app/forms/controls/select.html
projects/demo/src/app/forms/controls/text.html
projects/demo/src/app/forms/controls/textarea.html
projects/demo/src/app/forms/input-group/input-group.html
projects/demo/src/app/forms/layout/layout.html
projects/demo/src/app/radios/radios.demo.html
projects/demo/src/app/selects/selects.demo.html
projects/demo/src/app/textarea/textarea.demo.html
projects/demo/src/app/toggles/toggles.demo.html

closes #305
supersedes #308
Bugfix
Issue Number: #305
The validation icon and text are the same color.
No.

fix: ensure validation icons are the correct color

---

projects/angular/clarity.api.md
projects/angular/src/timeline/timeline-step.spec.ts
projects/angular/src/timeline/timeline-step.ts

fixes VPAT-13814
The icon needs role="img" for the aria-label to work properly
Issue Number: VPAT-13814

fix(timeline): add role="img" to timeline step icon

---

projects/angular/clarity.api.md
projects/angular/src/timeline/timeline-step.spec.ts
projects/angular/src/timeline/timeline-step.ts

Backports: 
https://github.com/vmware-clarity/ng-clarity/pull/319
https://github.com/vmware/clarity/pull/6697
VPAT-644,VPAT-13814
Issue Number: 
VPAT-644 VPAT-13814

fix(timeline): timeline-step accessibility fixes (backport)

---

.storybook/stories/card/card.stories.ts
.storybook/stories/header/header.stories.ts
.storybook/stories/list/list.stories.ts
projects/angular/src/layout/nav/_responsive-nav.clarity.scss

Bugfix
If you load the page on a medium width, the nav links AND the overflow triggers are both hidden.
If you load the page on a medium width, the overflow triggers are not hidden.
No

fix(header): show nav overflow triggers until correct breakpoint

---

.storybook/helpers/elements.data.ts
.storybook/stories/datagrid/datagrid-detail.stories.ts

Just a minor storybook change.

chore(datagrid): make long content optional in datagrid detail story

---

.storybook/stories/datagrid/datagrid-detail.stories.ts
projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/datagrid-if-detail.ts

closes #338
Bugfix
Feature
Issue Number: #338
The child datagrid column widths are correct.
No.

fix/feat(datagrid): prevent column width issues in child datagrids inside a parent datagrid's detail panel 

---

.storybook/stories/modal/modal.stories.ts
projects/angular/clarity.api.md
projects/angular/src/modal/modal.html
projects/angular/src/modal/modal.spec.ts
projects/angular/src/modal/modal.ts

Feature
The modal close button aria label is not customizable.
Issue Number: VPAT-758
The modal close button aria label is customizable.
No.

feat(modal): allow custom aria-label for close button

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid-column-toggle.ts
projects/angular/src/data/datagrid/providers/selection.spec.ts
projects/angular/src/data/datagrid/providers/selection.ts

chore(datagrid): remove unused constructor parameters

---

projects/angular/src/forms/datepicker/yearpicker.ts

chore(date-picker): remove unused private `decadeRange` property

---

projects/angular/src/popover/tooltip/tooltip-content.spec.ts

chore(tooltip): clean up tooltip component tests

---

projects/angular/clarity.api.md
projects/angular/src/popover/tooltip/tooltip-content.spec.ts
projects/angular/src/popover/tooltip/tooltip-content.ts

Bugfix
Tooltip content defaults are not applied correctly.
Issue Number: #370
Tooltip content defaults ar applied correctly.
No.

fix(tooltip): apply default size and position

---

projects/angular/src/forms/combobox/combobox.html

Currently the role=combobox is on the wrapper.
Issue Number: VPAT-2939
The role should be on the input field itself.
VPAT-2939

fix(combobox): move role to input element

---

projects/angular/clarity.api.md
projects/angular/src/data/tree-view/tree-focus-manager.service.spec.ts
projects/angular/src/forms/combobox/combobox-container.ts

chore: remove redundant properties

---

karma.conf.js

`npm run test:watch` does not launch a browser window.
`npm run test:watch` launches a browser window.
No

chore: resolve test watch option properly

---

angular.json
package.json
projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/_properties.datagrid.scss
projects/angular/src/data/datagrid/_variables.datagrid.scss
projects/angular/src/data/datagrid/datagrid-column-toggle.ts
projects/angular/src/utils/_theme.dark.clarity.scss
projects/angular/src/utils/i18n/common-strings.default.ts
projects/demo/src/environments/environment.dark.ts

Currently columns visibility is controlled in a menu triggered by a hard to understand and find button.
Issue Number: #43 
A button with text description is used instead
Visual only breaking change. No migration is needed besides updating visual regression tests, if such exist.

Datagrid, improve column selector button

---

angular.json
package.json
projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/_properties.datagrid.scss
projects/angular/src/data/datagrid/_variables.datagrid.scss
projects/angular/src/data/datagrid/datagrid-column-toggle.ts
projects/angular/src/utils/_theme.dark.clarity.scss
projects/angular/src/utils/i18n/common-strings.default.ts
projects/demo/src/environments/environment.dark.ts

This is a cherry-pick of #407 to `main`.
The show/hide column selector is not really obvious.
Issue Number: #43 
A button with text content is used instead of the icon button.
It's a visual breaking change. No need to update, unless user-side tests depend on the old icon button.

Improve column selector button in datagrid

---

.storybook/stories/datagrid/datagrid-detail.stories.ts
projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid-detail.ts

Rename.
Yes. The `closeCheck` method on `ClrDatagridDetail` has been renamed to `close`.

feat(datagrid): rename `closeCheck` method `close`

---

projects/angular/src/layout/nav/_properties.subnav.scss
projects/angular/src/layout/nav/_variables.subnav.scss
projects/angular/src/popover/dropdown/_variables.dropdown.scss
projects/angular/src/utils/_theme.dark.clarity.scss
projects/angular/src/utils/variables/_properties.typography.scss
projects/angular/src/utils/variables/_variables.typography.scss
projects/ui/src/shim.cds-core.scss

feat/chore: remove remaining references to the sidenav

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid-column-toggle.ts
projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
projects/angular/src/data/datagrid/datagrid-items.spec.ts
projects/angular/src/data/datagrid/datagrid.spec.ts
projects/angular/src/data/datagrid/providers/items.ts
projects/angular/src/data/datagrid/providers/selection.ts
projects/angular/src/forms/combobox/option-items.directive.spec.ts
projects/demo/src/app/datagrid/full/full.ts
projects/demo/src/app/datagrid/preserve-selection/preserve-selection.ts
projects/demo/src/app/datagrid/selection-single/selection-single.ts
projects/demo/src/app/datagrid/selection/selection.ts

chore(datagrid): improve `trackBy` function type annotations

---

.github/workflows/accept-merged-visual-changes.yml
.github/workflows/pr-visual-regression.yml

Chromatic does not rerun on lockfile and sass changes.
Chromatic reruns on lockfile and sass changes. 
- [ x] No

chore: update chromatic to rebuild on lockfile and sass changes

---

.storybook/stories/forms/forms.stories.ts
package-lock.json
package.json

Upgrades the core dependency that resolves a reported issue #502
https://github.com/vmware-clarity/core/commit/963987c3a084376718d99f9805812daa38dad35e
Issue Number: #502
#502 identified an issue with the dark mode typography color for input placeholders. That fix was landed in core@6.3.1, so this updates the dependency and introduces a story to validate the fix is applied.

chore: update @cds/core, add form story

---

.storybook/stories/combobox/combobox.stories.ts

This is backport of #550 to 13.x.

chore(combobox): filter options in story as user types (13.x backport)

---

projects/angular/clarity.api.md
projects/angular/src/button/all.spec.ts
projects/angular/src/button/button-group/button-group.html
projects/angular/src/button/button-group/button-group.ts
projects/angular/src/button/providers/button-group-focus-handler.service.ts
projects/angular/src/button/providers/button-group-focus-handler.spec.ts
projects/angular/src/button/providers/button-group-focus.enum.ts

- [ x ] Tests for the changes have been added (for bug fixes / features)
Bugfix
- [ x ] Bugfix
Keyboard navigation in Button Group menu is not working
Issue Number: CDE-68
Keyboard navigation once the menu in a Button Group is opened it's now working.
- [ x ] No

fix(button): add keyboard navigation in button-group menu

---

.storybook/stories/forms/forms-reactive.stories.ts
.storybook/stories/forms/forms-template-driven.stories.ts
projects/angular/src/forms/common/abstract-container.ts
projects/angular/src/forms/datepicker/date-container.spec.ts
projects/angular/src/forms/tests/container.spec.ts
projects/demo/src/app/forms/forms.demo.module.ts
projects/demo/src/app/forms/forms.demo.routing.ts
projects/demo/src/app/forms/forms.demo.ts
projects/demo/src/app/forms/reactive/reactive.ts
projects/demo/src/app/forms/template-driven/template-driven.ts

backport of https://github.com/vmware-clarity/ng-clarity/pull/548

fix(forms): fix template-driven forms validation regression (backport to 13.x)

---

.storybook/stories/button/button-group.stories.ts
projects/angular/clarity.api.md
projects/angular/src/button/button-group/button-group.html
projects/angular/src/button/button-group/button-group.spec.ts
projects/angular/src/button/button-group/button-group.ts

Adding an option to set custom "aria-label" for the toggle in button group.
Currently we have a default aria-label and custom one is not supported.

fix(button): custom aria label for button group menu toggle

---

.storybook/stories/button/button-group.stories.ts
projects/angular/clarity.api.md
projects/angular/src/button/button-group/button-group.html
projects/angular/src/button/button-group/button-group.spec.ts
projects/angular/src/button/button-group/button-group.ts

fix(button): custom aria label for button group menu toggle (backport to 13.x)

---

.github/workflows/pr-comment-bot.yml
.github/workflows/pr-preview.yml
.github/workflows/pr-visual-regression.yml

This makes the step ids consistent with each other and consistent with other yml casing.

chore: use kebab casing for workflow step ids

---

projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.ts
projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts

Disables autocomplete on datagrid column filter input 
Issue Number: CDE-72

fix(datagrid): disable autocomplete on filter input

---

projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.ts
projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts

fix(datagrid): disable autocomplete on filter input (backport to 13.x)

---

.github/workflows/accept-merged-visual-changes.yml
.github/workflows/label-stale-threads.yml
.github/workflows/lock-inactive-threads.yml
.github/workflows/pr-build.yml
.github/workflows/pr-comment-bot.yml
.github/workflows/pr-preview.yml
.github/workflows/pr-visual-regression.yml
.github/workflows/release-preview.yml
.github/workflows/release.yml

chore: update actions to avoid deprecated features

---

.github/workflows/pr-build.yml
.github/workflows/release-preview.yml
.github/workflows/release.yml

This is a backport of #584 to 13.x
No.

chore: update actions to avoid deprecated features (backport to 13.x)

---

projects/angular/clarity.api.md
projects/angular/src/button/all.spec.ts
projects/angular/src/button/button-group/button-group.html
projects/angular/src/button/button-group/button-group.ts
projects/angular/src/button/button-group/button.spec.ts
projects/angular/src/button/button-group/button.ts
projects/angular/src/button/providers/button-group-focus-handler.service.ts
projects/angular/src/button/providers/button-group-focus-handler.spec.ts
projects/angular/src/button/providers/button-group-focus.enum.ts
projects/angular/src/button/providers/button-in-group.service.spec.ts
projects/angular/src/utils/focus/focus.service.ts

Keyboard navigation in Button Group Menu is not working.
Issue Number: CDE-68
Keyboard navigation in Button Group Menu is working with arrows

fix(button): navigate menu via keyboard with focus

---

.storybook/stories/alert/alert.stories.ts
.storybook/stories/button/button-group.stories.ts
.storybook/stories/datagrid/datagrid-column.stories.ts
.storybook/stories/datagrid/datagrid.stories.ts
.storybook/stories/modal/modal.stories.ts
projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
projects/angular/src/layout/vertical-nav/vertical-nav.spec.ts
projects/angular/src/modal/modal.spec.ts
projects/angular/src/wizard/wizard-stepnav-item.spec.ts

chore: use `commonStringsDefault` instead of creating service instance

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid-row.html
projects/angular/src/data/datagrid/datagrid-row.spec.ts
projects/angular/src/data/datagrid/datagrid-row.ts

fix(datagrid): change label around clickable row (backport 13.x) (#626)

---

projects/angular/src/accordion/stepper/stepper-panel.spec.ts
projects/angular/src/data/datagrid/datagrid-column-toggle.spec.ts
projects/angular/src/data/datagrid/datagrid-detail.spec.ts
projects/angular/src/data/datagrid/datagrid-filter.spec.ts
projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
projects/angular/src/data/datagrid/datagrid.spec.ts
projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
projects/angular/src/layout/nav/header.spec.ts
projects/angular/src/layout/vertical-nav/vertical-nav.spec.ts
projects/angular/src/modal/modal.spec.ts
projects/angular/src/wizard/wizard-stepnav-item.spec.ts

This makes the tests directly assert the actual result.

chore: assert actual string values instead of common string values

---

projects/angular/src/accordion/API.md

API markdown file example for documenting css variables and class names used throughout components.

chore: add accordion api markdown example

---

.env
package.json

Environment variable for storybook is set inline from the terminal when the command is runned.
Removes the inline setting of environment variable for storybook because it's different for systems so using an .env file resolves the issue and it's native for nodejs.

feat: add env file to support multiple operating systems

---

.storybook/stories/datagrid/datagrid-expandable-row.stories.ts
projects/angular/src/utils/animations/expandable-animation/expandable-animation.ts

Expanding rows in Datagrid on Safari is overflowing.
The content is no longer overflowing outside the row.

fix(datagrid): expandable rows overflow on safari

---

.storybook/stories/datagrid/datagrid-expandable-row.stories.ts
projects/angular/src/utils/animations/expandable-animation/expandable-animation.ts

fix(datagrid): expandable rows overflow on safari ( backport to 13.x)

---

projects/angular/clarity.api.md
projects/angular/src/emphasis/alert/alerts-pager.html
projects/angular/src/emphasis/alert/alerts-pager.spec.ts
projects/angular/src/emphasis/alert/alerts-pager.ts
projects/angular/src/utils/i18n/common-strings.default.ts
projects/angular/src/utils/i18n/common-strings.interface.ts

backport of #610 
**removed "protected" from "alerts-pager.ts" as it's not availabe for use in the template before Angular 14 **

feat(alert): add aria labels for alerts pager (backport to 13.x)

---

.github/workflows/pr-build.yml
projects/angular/package.json

feat: add support for Angular 16

---

.storybook/stories/wizard/wizard-page.stories.ts
.storybook/stories/wizard/wizard.stories.ts
projects/angular/clarity.api.md
projects/angular/src/wizard/_wizard.clarity.scss
projects/angular/src/wizard/heading-level.ts
projects/angular/src/wizard/index.ts
projects/angular/src/wizard/test-components/api-wizard.mock.ts
projects/angular/src/wizard/wizard-title.ts
projects/angular/src/wizard/wizard.html
projects/angular/src/wizard/wizard.module.ts
projects/angular/src/wizard/wizard.spec.ts
projects/angular/src/wizard/wizard.ts

feat(wizard): support custom heading levels for titles (backport to 13.x)

---

.storybook/stories/wizard/wizard.stories.ts
projects/angular/clarity.api.md
projects/angular/src/utils/i18n/common-strings.default.ts
projects/angular/src/utils/i18n/common-strings.interface.ts
projects/angular/src/wizard/test-components/api-wizard.mock.ts
projects/angular/src/wizard/wizard.html
projects/angular/src/wizard/wizard.spec.ts
projects/angular/src/wizard/wizard.ts

feat(wizard): add custom aria-label for stepnav section (backport to 13.x)

---

projects/angular/src/forms/styles/_checkbox.clarity.scss
projects/angular/src/forms/styles/_radio.clarity.scss

Currently the hidden input for checkbox and radio button is improperly positioned on Firefox due to compatibility of "inline-block" on Firefox.  
Issue Number: CDE-243
Inputs are now properly aligned.

fix(forms): remove improper alignment of checkbox and radio on firefox

---

projects/angular/clarity.api.md
projects/angular/src/progress/progress-bars/progress-bar.ts
projects/angular/src/utils/popover/providers/popover-events.service.ts
projects/angular/src/utils/popover/providers/popover-position.service.ts

This is a backport of #702 to 13.x.

chore: remove unnecessary get/set accessors (backport to 13.x)

---

SECURITY.md

Adding security documentation policy.
No changes

chore: add security report policy

---

projects/angular/src/forms/combobox/STYLES.md

chore: css documentation for combobox

---

projects/angular/src/forms/datepicker/STYLES.md

chore: add datepicker css docs

---

projects/angular/src/progress/progress-bars/STYLES.md

chore: add progress bar css docs

---

projects/angular/src/forms/combobox/STYLES.md
projects/angular/src/layout/main-container/STYLES.md

chore: css documentation for main layout and headers

---

projects/angular/src/data/tree-view/STYLES.md

chore: add tree view css docs

---

projects/angular/src/typography/STYLES.md

chore: (lists) add CSS classes documentation

---

projects/angular/src/button/button-group/STYLE.md

chore(button group): add style documentation 

---

projects/angular/src/data/stack-view/STYLES.md

chore: add stack view css docs

---

projects/angular/src/popover/tooltip/STYLES.md

chore: css docs for tooltip

---

projects/angular/src/timeline/STYLES.md

chore: css documentation for timeline component

---

projects/angular/src/wizard/STYLES.md

chore: css documentation for wizard

---

projects/angular/src/forms/styles/_select.clarity.scss

fix(select): change caret color on hover (backport to 13.x)

---

projects/angular/src/data/datagrid/_datagrid.clarity.scss

fix(datagrid): change manage columns popover close button color on hover (backport to 13.x)

---

projects/angular/src/layout/vertical-nav/vertical-nav.html

fix(vertical-nav): add missing `type` attribute to close button

---

README.md

chore: add title to readme

---

.github/workflows/pr-backport.yml

chore: test pr backport 

---

projects/ui/src/token_shim.cds-core.scss

fix(tokens): add missing token colors

---

projects/angular/package.json

Update the angular library dependencies for the beta branch.

feat(angular): update dependencies

---

projects/angular/src/forms/styles/_datalist.clarity.scss
projects/angular/src/utils/variables/_variables.global.scss

Clicking over the caret icon in the datalist is not opening it
Clicking over it now opens datalist

fix(datalist): allow clicking over caret to open datalist

---

package-lock.json
package.json
projects/angular/package.json
projects/ui/package.json

Bumps @cds/core to the latest to incorporate bug fixes and incorrectly named tokens fixes. 
BREAKING CHANGE: Bumps cds/core dependency.

feat(deps): update cds/core

---

projects/angular/README.md

Updates the readme for the v16 changes.

chore(readme): update angular readme

---

projects/ui/src/shim.cds-core.scss

The shim file has a lot of potential for errors due to CSS variables and no compile time checking. 
Importing from the @cds/core/tokens/tokens.scss file allows us to get compile-time checking that CSS variables exist.

chore(ui): use scss vars for cds tokens in the shim

---

.github/workflows/release.yml

Sets up the beta branch to deploy the storybook site that is built from this branch during the release workflow.

chore(ci): auto deploy storybook to v16 site

---

projects/demo/src/app/selects/selects.demo.html
projects/demo/src/app/stepper/stepper.demo.html
projects/demo/src/app/stepper/stepper.demo.ts

chore(demo): add stepper scenario with clrIfExpanded directive and fix icon in select

---

projects/angular/src/emphasis/alert/_alert.clarity.scss

At certain media break the top-level alert pager sub-component will affect content following the alert.
Issue Number: CDE-1195
It does not affect content outside the alert container
This is fixed in v16 by providing different DOM structure for the container and pager. The current fix is for v15 only, as porting the whole v16 solution represents a breaking change.

fix(alert): top alert pager misalignment (v15 only)

---

projects/ui/src/shim.cds-core.scss

fix(tabs): add paddings and text size from tokens for overflow menu

---

projects/angular/src/layout/nav/_nav.clarity.scss
projects/angular/src/layout/nav/_responsive-nav.clarity.scss
projects/ui/src/shim.cds-core.scss

Revert changes from #953 and align responsive nav to vertical nav.

fix(header): revert changes and align subnav to vertical nav in cds-theme

---

.github/workflows/release.yml

Adds an automated release process for the v15 storybook branch to v15.storybook.clarity.design

chore(release): add v15 storybook to release

---

projects/angular/clarity.api.md
projects/angular/src/emphasis/alert/alert.ts
projects/angular/src/emphasis/alert/alerts.spec.ts
projects/demo/src/app/alert/angular/alert-angular-app-level-alerts.demo.html
projects/demo/src/app/alert/angular/alert-angular-app-level-alerts.ts

Using HostBinding for `alert-hidden` class Angular throws expression changed error which creates problems for unit tests in user projects
Issue Number: CDE-1249
Using `renderer` to set `alert-hidden` class on the host element manually which doesn’t have issues with change detection.

fix(alert): remove hostBinding and use renderer for alert-hidden class

---

projects/angular/src/utils/_mixins.scss

chore(typography): align token generation with design through mixin

---

projects/ui/src/shim.cds-core.scss

Since the title-font-weight value is not redeclared in the shim, the root value is computed and used.
Issue Number: CDE-1283

fix(card): update card header to correct font-weight (v15 backport)

---

package.json
projects/angular/src/forms/styles/containers.spec.ts
projects/angular/src/progress/spinner/spinner.spec.ts
projects/angular/src/test.ts
projects/demo/src/app/cds-theme-select.component.ts
projects/ui/src/shim.cds-core.scss

chore: unit tests to use cds theme

---

projects/angular/clarity.api.md
projects/angular/src/accordion/accordion-panel.ts
projects/angular/src/accordion/accordion.ts

The EventEmitter type was missing. This isn't a big issue for developers as the type is easily inferred, but the Storybook Docs tab doesn't infer the correct type. 
The correct type is specified, and descriptions are added to inputs/outputs to be parsed by Storybook.

fix(accordion): update event type and add descriptions

---

projects/ui/src/shim.cds-core.scss

Since the title-font-weight value is not redeclared in the shim, the root value is computed and used.
Issue Number: CDE-1283

fix(card): update card header to correct font-weight (port of #980)

---

projects/ui/src/shim.cds-core.scss

fix(label): remove has pseudo class selector (port of #1020)

---

projects/angular/clarity.api.md
projects/angular/src/data/tree-view/tree-node.html
projects/angular/src/data/tree-view/tree-node.ts
projects/ui/src/shim.cds-core.scss

fix(tree-view): remove has css selector (port of #1020)

---

projects/angular/src/popover/signpost/signpost-content.ts

When you open a signpost with a scroll you can't use keyboard due to missing focus on the content.
Issue Number: CDE-1397
Now you can focus the content and scroll freely with the keyboard.

fix(signpost): allow keyboard scrolling in overflow content

---

projects/angular/src/data/datagrid/datagrid-row.html

fix(datagrid): add role gridcell to detail caret

---

projects/angular/src/forms/combobox/STYLES.md

fix(combobox): remove forgotten style doc

---

projects/angular/src/forms/styles/_range.clarity.scss

fix(range): remove unnecessary thumb positioning for firefox

---

projects/angular/src/forms/styles/_range.clarity.scss

fix(range): remove unnecessary thumb positioning for firefox (port of #1055)

---

projects/angular/src/popover/tooltip/STYLES.md
projects/angular/src/popover/tooltip/_properties.tooltip.scss
projects/angular/src/popover/tooltip/_tooltips.clarity.scss
projects/angular/src/popover/tooltip/_variables.tooltip.scss
projects/ui/src/shim.cds-core.scss

feat(tooltip): remove shim and fallbacks

---

projects/angular/clarity.api.md
projects/angular/src/forms/common/wrapped-control.spec.ts
projects/angular/src/forms/common/wrapped-control.ts
projects/demo/src/app/forms/dynamic-controls/dynamic-controls.demo.html
projects/demo/src/app/forms/dynamic-controls/dynamic-controls.demo.ts
projects/demo/src/app/forms/forms.demo.module.ts
projects/demo/src/app/forms/forms.demo.routing.ts
projects/demo/src/app/forms/forms.demo.ts

feat(forms): support for dynamic control change (#1074)

---

projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss

chore(vertical-nav): negative margin content

---

projects/angular/src/layout/nav/_links.clarity.scss
projects/angular/src/utils/_reboot.clarity.scss
projects/demo/src/app/typography/typography-links.html

Visited hover color is same as visited.
Issue Number: CDE-1561
Visited hover color is changed to visited hover.

fix(links): change  visited hover saas variable

---

.github/workflows/delete-stale-branches-preview.yml
.github/workflows/delete-stale-branches.yml

Deletes stale visual snapshot branches on manual trigger.
Not deleting them anyway.
Issue Number: CDE-1562

chore(ci): delete stale visual snapshot branches workflow

---

projects/angular/src/forms/styles/_input-group.clarity.scss

CDE-1605
closes #559
Bugfix
No pointer cursor for input action buttons (datepicker, password show/hide).
Issue Number: CDE-1605, #559
Pointer cursor for input action buttons (datepicker, password show/hide).
No.

fix(input): use "pointer" cursor for input action buttons

---

projects/angular/src/forms/styles/_input-group.clarity.scss

This is a port of 5272eccf365ef7e083874c57d48e28bdf2dcf9c9 (#1153) to 15.x.
CDE-1605
closes #559
Bugfix
No pointer cursor for input action buttons (datepicker, password show/hide).
Issue Number: CDE-1605, #559
Pointer cursor for input action buttons (datepicker, password show/hide).
No.

fix(input): use "pointer" cursor for input action buttons (port to 15.x)

---

projects/angular/src/forms/datepicker/providers/date-io.service.ts

If Date object is passed to the control and that's being passed to 'getDateValueFromDateString' which accepts strings only -- the control breaks and freezes. 
Issue Number: CDE-1578
Ignore non-string values which are passed to that function.

fix(date-picker): ignore non-string values in date service parser

---

README.md

Adds Assistiv Labs to readme to explore open source license.

chore: add assistiv labs to readme

---

projects/demo/src/app/i18n-a11y/i18n-a11y.demo.html

This change removes the "VoiceOver is stupid" comment.

chore: reword text about VoiceOver behavior

---

projects/angular/src/forms/common/wrapped-control.spec.ts

chore(forms): simplify wrapped control aria-describedby tests

---

tests/screenshot-options.ts

There is no description of the screenshot-options file or functionality
Adds a comment describing the purpose of the screenshot options file and how to add or update an option.

chore(screenshot): add comment to screenshot options

---

.github/workflows/pr-build.yml
projects/angular/package.json

Issue Number: CDE-1597
This is not exactly port (as it was not cherrypicked) but it adds the same change as this PR: https://github.com/vmware-clarity/ng-clarity/pull/1094
Tested with this PR: https://github.com/vmware-clarity/ng-clarity/pull/1313

feat: add support for Angular 17

---

.storybook/stories/button/button-group.stories.ts
.storybook/stories/button/button.stories.ts
.storybook/stories/button/buttons-loading.stories.ts
.storybook/stories/combobox/combobox.stories.ts
.storybook/stories/datagrid/modal-stacked-on-detail.stories.ts
.storybook/stories/datagrid/nested-detail-in-detail.stories.ts
.storybook/stories/datalist/datalist.stories.ts
.storybook/stories/datepicker/date-container.stories.ts
.storybook/stories/datepicker/datepicker.stories.ts
.storybook/stories/dropdown/dropdown-item-that-opens-modal.stories.ts
.storybook/stories/dropdown/dropdown-menu.stories.ts
.storybook/stories/dropdown/dropdown-static.stories.ts
.storybook/stories/dropdown/dropdown-tree.stories.ts
.storybook/stories/dropdown/dropdown.stories.ts
.storybook/stories/forms/forms-input-states.stories.ts
.storybook/stories/forms/forms-reactive.stories.ts
.storybook/stories/forms/forms-required-mark.stories.ts
.storybook/stories/forms/forms-template-driven.stories.ts
.storybook/stories/modal/nested-datagrid-detail.stories.ts
.storybook/stories/modal/nested-popover.stories.ts
.storybook/stories/modal/stacked-modal.stories.ts
.storybook/stories/radio/radio-container.stories.ts
.storybook/stories/radio/radio.stories.ts
.storybook/stories/spinner/spinner.stories.ts
.storybook/stories/stepper/stepper.stories.ts

This change prevents confusion with package imports.

chore: use relative file path import for story helpers

---

projects/angular/clarity.api.md
projects/angular/src/forms/radio/radio-container.ts

Issue Number: [CDE-1196](https://jira.eng.vmware.com/browse/CDE-1196)
Screen reader will announce the label added to the radio group on focus.

fix(a11y): screen reader does not announce label for radio group

---

projects/angular/src/forms/combobox/_combobox.clarity.scss

fix(combobox): hide scrollbar if not needed

---

.storybook/stories/login/login.stories.ts

chore(storybook login): import common modules to allow controls to work

---

projects/angular/src/forms/radio/radio-container.ts

The a11y role for the radiogroup control was set as `group`
Issue Number: CDE-1196
Based on discussions with the accessibility team,  updated the role to the more specific `radiogroup` role.

fix(a11y): update role to radiogroup for radio group control

---

projects/angular/src/forms/styles/_containers.clarity.scss
projects/angular/src/forms/styles/_radio.clarity.scss

fix(forms): compact layout alignment fixes

---

projects/angular/src/data/tree-view/recursive-children.ts

The screen reader is reading out incorrect levels in case of a recursive tree view component.
Issue Number: CDE-1697
The screen reader will read out correct levels for the recursive tree view

fix(a11y): treeview incorrect levels

---

.storybook/preview.js
projects/angular/src/forms/combobox/combobox.html
projects/angular/src/forms/datepicker/datepicker-view-manager.html
projects/demo/src/app/datepicker/datepicker-min-max.html
projects/demo/src/app/typography/typography-font-autopsy.html
projects/demo/src/app/typography/utils/font-switcher.html

chore: update missed licensed files

---

projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/datagrid.html

Currently loading rows are using `clr-dg-row` which shows the sticky columns if available
10](https://github.com/vmware-clarity/ng-clarity/assets/127101685/0fb09866-ea69-4679-9d8f-d1a691ae4a65)
Issue Number: CDE-2069
Hide sticky columns for loading row.

fix(datagrid): hide sticky columns for loading more items row (#1420)

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid-detail.ts

Change detector is added in #1431 and is unused.
Issue Number: CDE-2070
Change detector is removed.

chore(datagrid): remove unused change detector from details

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid.ts
projects/angular/src/data/datagrid/enums/column-changes.enum.ts
projects/angular/src/data/datagrid/providers/columns.service.ts
projects/angular/src/data/datagrid/render/cell-renderer.ts
projects/angular/src/data/datagrid/render/main-renderer.ts

Changing the page with detail open closes the detail and the columns which were hidden are still hidden.
Issue Number: CDE-2067
Columns will be visible again once the detail is closed.

fix(datagrid): previously hidden columns visible after detail close

---

projects/angular/src/forms/common/abstract-container.ts

Currently on the first blur 'showInvalid' is false initially because the error component is rendered after updating the helpers.
Issue Number: CDE-700
Wraps the update of helpers in a setTimeout to make sure component is rendered.

fix(forms): add error id in aria-describedby on first blur

---

projects/angular/src/forms/styles/_properties.forms.scss

Border color on disabled select is disappearing on hover.
Using the correct token and it's still visible.

fix(select): use correct token for disabled border on hover

---

projects/angular/src/data/datagrid/datagrid-if-detail.ts

chore(datagrid): remove missed console log

---

projects/angular/src/data/datagrid/all.spec.ts
projects/angular/src/data/datagrid/datagrid-detail.spec.ts

These tests were not being run before. This commit corrects the tests and includes them in the "all" file for execution.

chore(datagrid): add datagrid detail tests in "all" file

---

projects/angular/src/layout/nav/_variables.responsive-nav.scss
projects/angular/src/utils/variables/_variables.global.scss
projects/demo/src/styles.scss

Issue Number: CDE-2109
Revert a css-variables API regression introduced with 17.2.0

fix: revert sidepanel z-index variables

---

projects/angular/src/accordion/stepper/stepper-panel.ts
projects/angular/src/accordion/stepper/stepper.spec.ts
projects/demo/src/app/stepper/stepper.demo.html
projects/demo/src/app/stepper/stepper.demo.ts

fix(stepper): set panel validation after input touched

---

projects/angular/src/layout/grid/STYLES.md
projects/angular/src/layout/grid/grid/_grid.scss
projects/angular/src/layout/grid/mixins/_grid-framework.scss
projects/angular/src/layout/grid/mixins/_grid.scss
projects/angular/src/utils/variables/_properties.layout.scss
projects/angular/src/utils/variables/_properties.scss
projects/angular/src/utils/variables/_variables.layout.scss
projects/demo/src/app/grid/grid.demo.module.ts
projects/demo/src/app/grid/grid.demo.routing.ts
projects/demo/src/app/grid/grid.demo.scss
projects/demo/src/app/grid/grid.demo.ts
projects/demo/src/app/grid/overflow/grid-container.html
projects/demo/src/app/grid/overflow/grid-container.ts

Adds the container mixin used in boostrap to wrap rows ad columns and additional tokens to control spacings inside

feat(grid): add container class and tokens

---

.storybook/stories/dropdown/dropdown-static.stories.ts

Storybook example for the static dropdown does not have proper aria attributes.
Issue Number: [CDE-1059](https://jira.eng.vmware.com/browse/CDE-1059)
Updated the storybook example for the static dropdown with aria attribute support.

chore(a11y): add aria menu code structure for static dropdown story

---

projects/angular/src/emphasis/alert/_alert.clarity.scss
projects/angular/src/emphasis/alert/_variables.alert.scss

States `:hover` and `:click` background and text colors are wrong. Regression is added with #1445 
Issue Number: CDE-2211
App level action button states `:hover` and `:click` background and text colors are using respective outline button colors.

fix(alert): app level action buttons hover and active colors

---

.github/workflows/pr-build.yml
projects/angular/package.json
projects/angular/src/data/datagrid/datagrid-detail.spec.ts
projects/angular/src/data/datagrid/datagrid.spec.ts
projects/angular/src/forms/datepicker/monthpicker.spec.ts
projects/angular/src/forms/datepicker/yearpicker.spec.ts

There is no Angular 18 support.
There is Angular 18 support.
I took https://github.com/vmware-clarity/ng-clarity/pull/1094 as reference.

feat: add support for Angular 18

---

CHANGELOG.md
projects/angular/src/forms/combobox/_combobox.clarity.scss
projects/ui/src/shim.cds-core.scss

Backport bb5dafeae4f74f829d16aac97faabe4b48c14114 from #1508. <br> ## PR Checklist
- Combobox text line height is relative to parent.
Issue Number: CDE-2232
- Combobox text line height is seto 20px equal to regular body line height.

fix(modal): backdrop click focus to title (backport to 16.x)

---

.github/workflows/release.yml
.releaserc.js
docs/PUBLISHING.md
package-lock.json
package.json

The Slack channel is readonly now prior to the Slack instance being shut down.

chore(ci): remove Slack post from release process

---

projects/angular/clarity.api.md
projects/angular/src/layout/nav/_responsive-nav.clarity.scss
projects/angular/src/layout/nav/nav-level.spec.ts
projects/angular/src/layout/nav/nav-level.ts

Prerequisite for CDS merge task

Drop cds-internal-close-button dependency from responsive nav

---

README.md

chore: update to uppercase S in readme for BrowserStack

---

projects/angular/src/data/datagrid/datagrid.ts

If you change the items inside datagrid trough outside filter and previously it was clicked on any cell then the datagrid will steal the focus.
Issue Number: CDE-2273 #1542
Keep focus on the element

fix(datagrid): skip focusing active cell if focus outside component

---

projects/angular/src/accordion/stepper/_stepper.clarity.scss
projects/demo/src/app/stepper/stepper.demo.html

When nested in stepper accordion have different than specification look and feel.
- Header is taller 
- Text is bolder
- Have stepper number
- Text is aligned with stepper's text
Issue Number: CDE-2275
When nested in stepper accordion header have specification based styles and behaviour.

fix(stepper): nested accordion have wrong styling and behaviour

---

projects/angular/src/layout/nav/_links.clarity.scss

Icons inside link are not colored once state is visited
Issue Number: CDE-2285
Icons are now using visited color token.

fix(link): set interactions colors on icons inside links

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid.spec.ts
projects/angular/src/data/datagrid/datagrid.ts

fix(datagrid): update detail state on initialization (backport to 16.x)

---

projects/angular/src/button/_properties.buttons.scss
projects/angular/src/button/_properties.toggles.scss
projects/angular/src/emphasis/_properties.badges.scss
projects/angular/src/emphasis/_properties.label.scss
projects/angular/src/emphasis/alert/_properties.alert.scss
projects/angular/src/forms/combobox/_properties.combobox.scss
projects/angular/src/forms/datepicker/_properties.datepicker.scss
projects/angular/src/layout/tabs/_properties.tabs.scss
projects/angular/src/layout/vertical-nav/_properties.vertical-nav.scss
projects/angular/src/modal/_properties.modal.scss
projects/angular/src/popover/dropdown/_properties.dropdown.scss
projects/angular/src/progress/spinner/_properties.spinner.scss
projects/angular/src/wizard/_properties.wizard.scss
projects/ui/src/temp-overrides.scss

There are different structures trough the files.
Have the same structure

chore(properties): align files to have the same structure

---

projects/ui/src/temp-overrides.scss

`--cds-alias-viz-severity-warning-light` doesnt not exist.
Issue Number: CDE-2377
`--cds-alias-viz-severity-warning-light` is added for both light and dark themes.

feat(token): add viz alias for severity warning light

---

projects/angular/src/layout/nav/_properties.responsive-nav.scss
projects/angular/src/layout/nav/_variables.responsive-nav.scss
projects/angular/src/layout/vertical-nav/_properties.vertical-nav.scss
projects/ui/src/temp-overrides.scss

Issue Number: CDE-2387
Rename `--cds-alias-object-vertical-navigation-background-color` tokens to `cds-alias-object-interaction-background-shade`.
Remove unused overrride tokens:
- `--clr-nav-background-color`
- `--cds-global-color-blue-25`
- `--cds-alias-viz-severity-warning-light`

fix(tokens): update alias overrides and remove unused

---

projects/angular/src/data/datagrid/datagrid-column.spec.ts
projects/angular/src/data/datagrid/datagrid-column.ts
projects/demo/src/app/datagrid/sorting/sorting.html
projects/demo/src/app/datagrid/sorting/sorting.ts

Reverts vmware-clarity/ng-clarity#1612

Revert "feat(datagrid): add ability to unsort columns"

---

projects/angular/src/popover/tooltip/_tooltips.clarity.scss
projects/angular/src/popover/tooltip/_variables.tooltip.scss

Spacing between trigger and tooltip pointer arrow is 12px.
Issue Number: CDE-2479
Spacing between trigger and tooltip pointer arrow is 8px.

fix(tooltip): adjust distance from trigger from 12px to 8px

---

projects/angular/src/layout/breadcrumbs/breadcrumbs.html

Issue Number: [CDE-2575](https://vmw-jira.broadcom.net/browse/CDE-2575)

fix(breadcrumbs): add default target when no target is available

---

projects/angular/src/data/datagrid/datagrid.ts
projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
projects/demo/src/app/datagrid/virtual-scroll-client-side/virtual-scroll-client-side.html
projects/demo/src/app/datagrid/virtual-scroll-client-side/virtual-scroll-client-side.ts

Keep focus on the element, but brake virtual scroll key navigation.
Issue Number: CDE-2564, CDE-2237, follow up of PR #1545
Keep focus on the element in all cases without side effects.

fix(datagrid): skip focusing active cell if focus is outside component

---

.storybook/stories/datagrid/datagrid-virtualscroll-detail.stories.ts
.storybook/stories/datagrid/datagrid-virtualscroll.stories.ts
projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.spec.ts
projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.ts
projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
projects/demo/src/app/datagrid/virtual-scroll-client-side/virtual-scroll-client-side.html
projects/demo/src/app/datagrid/virtual-scroll-server-side/virtual-scroll-server-side.html

Current virtual scroll selector follow `Pascal Case` pattern.
Virtual scroll selector follow `Camel Case` pattern.
The original `Pascal Case` pattern is still supported, but deprecated.

fix(datagrid): update datagrid virtual scroll selector name

---

projects/angular/clarity.api.md
projects/angular/src/forms/datepicker/yearpicker.ts

Only the current month and current date is highlighted. As part of this change current year also will be highlighted with border around it.

fix(datepicker): highlight current year

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.ts
projects/angular/src/data/datagrid/datagrid.html
projects/angular/src/data/datagrid/datagrid.ts

Exposing Viatual Scroller to Datagrid.
Removing redundant `hasVirtualScroller`.

chore(datagrid): expose virtual scroller to datagrid for ease of access

---

projects/angular/src/forms/datepicker/_properties.datepicker.scss
projects/angular/src/forms/datepicker/day.ts

…border
Issue Number: [CDE-2552](https://vmw-jira.broadcom.net/browse/CDE-2552)
1. Update Calendar container background color.
2. Daterangepicker hovered cell have rounded corners from selection side.

fix(datepicker): update calendar border color and remove day hover rounded border

---

.storybook/stories/datagrid/datagrid-virtualscroll.stories.ts

follow up of #1719 
1. add accidently deleted event 
2. remove not used variable

chore(datagrid): update virtual scroll story

---

projects/angular/src/data/datagrid/_datagrid.clarity.scss

Small interaction area for expand caret, detail caret and row actions button.
Issue Number: CDE-2614
Increased interaction area for expand caret, detail caret and row actions button.

fix(datagrid): increase interaction area for row actions cells

---

.github/workflows/pr-comment-bot.yml

chore: add open in stackblitz in pr bot comment

---

.github/workflows/update-preview-build-branches.yml

chore: allow manual trigger for preview build branches

---

projects/angular/src/accordion/accordion-panel.html
projects/angular/src/accordion/accordion-panel.spec.ts

Issue Number: CDE-2632
aria-controls hides when accordion collapse

fix(accordion): set aria-controls behavior

---

projects/angular/src/forms/datepicker/_datepicker.clarity.scss

For lower screen resolutions, month view alignment in not proper. It aligns in single column.
Issue Number: [CDE-2636](https://vmw-jira.broadcom.net/browse/CDE-2636)

fix(datepicker): alignment fixes for lower screen resolution

---

projects/angular/src/forms/number-input/number-input.module.ts

fix(number-input): include plus and minus icons in the module

---

projects/angular/clarity.api.md
projects/angular/src/data/tree-view/_tree-view.clarity.scss
projects/angular/src/data/tree-view/tree-node.html
projects/angular/src/data/tree-view/tree-node.ts
projects/angular/src/emphasis/_labels.clarity.scss

Issue Number: CDE-1395
Reintroduce `:has` pseudo selector for internal usage.

fix(label, tree-view): reintroduce `:has` pseudo selector

---

projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss

fix(vertical-nav): top-level links font-weight

---

.storybook/helpers/render-component.ts
.storybook/stories/badge/badge.storybook.component.ts

chore: render nested components without host selector

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/_datagrid.clarity.scss
projects/angular/src/data/datagrid/datagrid-row.html
projects/angular/src/data/datagrid/datagrid-row.spec.ts
projects/angular/src/data/datagrid/datagrid-row.ts
projects/angular/src/utils/animations/constants.ts
projects/angular/src/utils/animations/expandable-animation/base-expandable-animation.ts
projects/angular/src/utils/animations/expandable-animation/expandable-animation.directive.ts
projects/angular/src/utils/animations/expandable-animation/expandable-animation.spec.ts
projects/angular/src/utils/animations/expandable-animation/expandable-animation.ts
projects/angular/src/utils/animations/expandable-animation/index.ts

Simplifying datagrid-row template and allow what we are trying to implement in #1791 which is currently not possible due to the multiple content projections inside datagrid-row that are creating issue between Calculate and Display modes for datagrid.

feat(datagrid): use expandable animation directive instead component

---

projects/angular/clarity.api.md
projects/angular/src/wizard/wizard-stepnav-item.ts

Reverts 477ae2fcd8aaa5664c06dfb392a303d8e3ac6747 (#1831)
This needs some more work.

Revert "fix(wizard): scroll step into view when current step changes"

---

projects/angular/src/layout/density/_properties.density.scss
projects/angular/src/layout/density/_variables.density.scss
projects/demo/src/app/layout/layout-size.html
projects/demo/src/app/layout/layout-size.ts

feat(density): add multi row tokens

---

tests/visual-snapshots.spec.ts

chore: use density property in storyParams for visual tests

---

.github/workflows/pr-build.yml
tests/visual-snapshots.spec.ts

chore: shard visual regression tests by theme and density

---

projects/angular/src/layout/density/_properties.density.scss
projects/angular/src/layout/density/_variables.density.scss

We don't have 24px gap token.
Issue Number: CDE-2864
clr-base-gap-xl becomes 24px
new clr-base-gap-2xl is introduced for 32px

feat(density): add 2xl gap token

---

projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.spec.ts
projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.spec.ts
projects/angular/src/data/datagrid/utils/key-navigation-utils.ts
projects/angular/src/utils/testing/helpers.spec.ts

 fix(datagrid): calculate average height for pageUp and pageDown navigation

---

projects/angular/clarity.api.md
projects/angular/src/data/datagrid/datagrid.module.ts
projects/angular/src/data/datagrid/helpers.spec.ts
projects/angular/src/data/datagrid/index.ts
projects/angular/src/data/datagrid/render/main-renderer.ts
projects/angular/src/data/datagrid/render/row-detail-renderer.ts
projects/angular/src/data/datagrid/render/row-renderer.ts
projects/demo/src/app/datagrid/expandable-rows/expandable-rows.html

fix(datagrid): resizing columns in expanded rows not updating row details

---

.storybook/stories/dropdown/dropdown-menu.stories.ts
projects/angular/src/button/button-group/button.ts

Remove content wrapper intruced in #1860 
Issue Number: CDE-2956

fix(button-group): remove content wrapper

---

.github/workflows/pr-build.yml
.github/workflows/pr-preview.yml

chore(ci): update pr preview to checkout pr branch

---

.github/workflows/pr-build.yml
.github/workflows/pr-preview.yml

chore(ci): update pr preview to checkout pr branch (#2011) (backport to next) 

---

.github/workflows/pr-preview.yml
.github/workflows/pr-visual-snapshot-update-bot.yml

chore: use github owned actions for artifacts and status (#2020) (backport to main)

---

.github/workflows/pr-preview.yml
.github/workflows/pr-visual-snapshot-update-bot.yml

Some of the old parameters were left behind due to some merge conflicts. Now removing them.

chore: remove unknown params from artifacts step

---

.github/workflows/pr-preview.yml
.github/workflows/pr-visual-snapshot-update-bot.yml

chore: use compatible versions for download and upload artifacts

---

.github/workflows/pr-preview.yml
.github/workflows/pr-visual-snapshot-update-bot.yml

chore: add permissions and edit parameters on workflows

---

.github/workflows/pr-preview.yml
.github/workflows/pr-visual-snapshot-update-bot.yml

chore: use proper property names and permissions for workflows

---

.github/workflows/pr-preview.yml
.github/workflows/pr-visual-snapshot-update-bot.yml

chore: add permission to snapshot update workflow and doc check step on preview

---

.github/workflows/pr-comment-bot.yml

chore: typo on check for docs comment bot

---

.github/workflows/pr-preview.yml

chore: use proper path for download artifact steps
