vmware-clarity/ng-clarity

- projects/angular/clarity.api.md
- projects/angular/src/forms/password/password-container.spec.ts
- projects/angular/src/forms/password/password-container.ts
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
Backport https://github.com/vmware/clarity/pull/6648
I'm fixing a related VPAT, so backporting this to v12
Fixes VPAT-667, VPAT-5242
> (backport) fix(password): add screen-reader only text for password

- projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
The link text is set to display:none when collapsed, which is invisible to screen readers
use the screen-reader-only mixin so the link text is visible to screen readers
> fix(vertical-nav): use sr-only css for collapsed link text

- projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
The link text is set to display:none when collapsed, which is invisible to screen readers
use the screen-reader-only mixin so the link text is visible to screen readers
> (backport) fix(vertical-nav): use sr-only css for collapsed link text

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.spec.ts
- projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.ts
- projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
- projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
- projects/angular/src/data/datagrid/datagrid-column.ts
Fixing VPAT-9616 
Provide a way to pass `placeholder` and `aria-label` to both build-in filters `String` & `Number` this way the requirement for a uniqueness for filters could be covered. 
If no custom text is passed, a default translation will be set.
> fix: provide a way to change placeholder and aria-label for builtin filters

- package.json
Stylelint ignores dot folders such as ".storybook". This PR makes it so any dot folders that aren't specifically excluded are picked up. This keeps the build process in sync with the changes we're making to the Core repo.
> chore: match dot folders with stylelint

- projects/angular/clarity.api.md
- projects/angular/src/layout/nav/aria-current-link.spec.ts
- projects/angular/src/layout/nav/aria-current-link.ts
- projects/angular/src/layout/nav/index.ts
- projects/angular/src/layout/nav/navigation.module.ts
- projects/demo/src/app/app.component.html
- projects/demo/src/app/content-container.component.ts
Addresses VPAT-628 to programmatically add aria-current="page" to the current nav link
**Enable  aria-current functionality for nav links using by introducing the  `clrAriaCurrentLink` directive.** 
`clrAriaCurrentLink` directive works as utility to denote the current link with `aria-current="page"` if it matches the active router link. It uses the `RouterLinkActive` director to subscribe to the change in active status.
It can be appended to any nav link that uses the `routerLink` and `routerLinkActive` directive. Works with the header, subheader, sidenav and vertical nav
> feat(nav): add clrAriaCurrentLink directive for nav links

- projects/angular/src/forms/datepicker/calendar.html
The first half of the vpat-661 for providing headers for days inside the calendar.
> fix: datepicker 'days' row is not set as table header

- projects/angular/src/forms/combobox/combobox.html
- projects/angular/src/utils/popover/popover-content.spec.ts
• moved combobox role to span wrapper
• removed aria-multiline
• see VPAT-2939
• also fixed breaking popover test.
Signed-off-by: Scott Mathis <smathis@vmware.com>
Moves the `role="comobox"` off the combobox `input` element and onto a wrapper (per a11y). Removes the `aria-multiline` attribute (also per a11y).
Also fixes a failing `popover-content` unit test. A datepicker test wasn't cleaned up so it was confusing the lookup in the test. I made the lookup in the popover-content test more specific but also had to re-lookup after change. 
see VPAT-2939
Issue Number: VPAT-2939
> fix(combobox): update aria attrs for clr-combobox

- projects/angular/src/forms/combobox/combobox.html
removed aria-multiline. moved role attr to wrapper. per a11y. see vpat-2939
Signed-off-by: Scott Mathis <smathis@vmware.com>
backport of https://github.com/vmware-clarity/ng-clarity/pull/85
> fix(combobox): backport combobox a11y changes

- projects/angular/src/layout/nav/_responsive-nav.clarity.scss
Because the button is positioned outside of the area of the navigation overflow hides the button.
Issue Number: #97 
The Close button is now visible because of the overflow updated value.
> fix(navigation): visibility of close button in tablet and mobile view

- package-lock.json
- projects/angular/src/utils/variables/_variables.global.scss
- projects/demo/src/app/app.routing.ts
- projects/demo/src/app/z-index/custom-filter.demo.ts
- projects/demo/src/app/z-index/various-content/various-content.html
- projects/demo/src/app/z-index/various-content/various-content.ts
- projects/demo/src/app/z-index/z-index.demo.html
- projects/demo/src/app/z-index/z-index.demo.module.ts
- projects/demo/src/app/z-index/z-index.demo.ts
- projects/demo/src/app/z-index/z-index.routing.ts
closes #111
We have hard coded z-index positions for too many types of elements. This statically fixes what is displayed over and under other elements. In some cases, this is necessary. But for many nesting scenarios, it leads to failures.
Issue Number: #111
Several types of elements were reworked to use the same level of z-index. This leads to the browser more flexibly overlaying different elements, based on their position in the DOM tree.
I have added visual pages (for which automated visual regression tests may be done once we create such) for the following scenarios and combinations:
Nested elements (which have their own overlays): …
> fix: fix multiple overlay nesting scenarios

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
It should be grey, not blue
Fixes #130
> fix(datagrid): update detail pane close icon color to match modal

- projects/angular/src/modal/modal-body.ts
This is a backport of #5.
Requested here: https://github.com/vmware-clarity/ng-clarity/commit/b95729e6447b8f3180969fef939e10910dd62771#commitcomment-74553929
> fix(modal): disconnect the resize observer once the modal body is removed (v12 backport)

- projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
- projects/angular/src/data/datagrid/datagrid-row-detail.ts
fixes VPAT-601
the detail pane exists inside of a role="gridrow" element, but is not denoted as a cell, which is incorrect semantically
Issue Number: VPAT-601
Now it's a gridcell to match the semantic requirements (all of the issues with expandable rows in a datagrid still exist)
> fix(datagrid): add role=gridcell to row detail element

- projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
- projects/angular/src/data/datagrid/datagrid-row-detail.ts
fixes VPAT-601
the detail pane exists inside of a role="gridrow" element, but is not denoted as a cell, which is incorrect semantically
Issue Number: VPAT-601
Now it's a gridcell to match the semantic requirements (all of the issues with expandable rows in a datagrid still exist)
> fix(datagrid): add role=gridcell to row detail element (backport)

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-action-overflow.ts
- projects/angular/src/utils/index.ts
- projects/angular/src/utils/list-key-navigation/index.ts
- projects/angular/src/utils/list-key-navigation/key-navigation-list.module.ts
- projects/angular/src/utils/list-key-navigation/key-navigation-list.spec.ts
- projects/angular/src/utils/list-key-navigation/key-navigation-list.ts
- projects/angular/src/utils/list-key-navigation/providers/focusable-items.ts
- projects/angular/src/utils/list-key-navigation/providers/key-navigation-list.config.ts
- projects/angular/src/utils/list-key-navigation/utils.ts
- projects/demo/src/app/datagrid/datagrid.demo.module.ts
- projects/demo/src/app/datagrid/full/full.html
By [w3c specification](https://w3c.github.io/aria-practices/examples/menu-button/menu-button-links.html) role menu has to have keyboard navigation with arrow keys. At the moment the overflow menu in datagrid doesn't support this by default.
Issue Number: VPAT-600
By using the `clrKeyNavigationList` directive on the container all clickable/focusable elements inside the container will be able to focus with arrow key.
> Adding utils for key navigation in list/menu 

- .github/workflows/bot.yml
The event sender may not be the person who opened the pull request.
If another user pushes to the pull request, I think it would be better not to change the name in the bot's comment.
(This is just a GitHub Actions workflow change.)
> chore: use correct name in pull request bot comments

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
- projects/angular/src/data/stack-view/_stack-view.clarity.scss
- projects/demo/src/app/app.routing.ts
- projects/demo/src/app/overlay-clipping/overlay-clipping.demo.html
- projects/demo/src/app/overlay-clipping/overlay-clipping.demo.module.ts
- projects/demo/src/app/overlay-clipping/overlay-clipping.demo.ts
- projects/demo/src/app/overlay-clipping/overlay-clipping.routing.ts
I've added manual visual tests (to be automated in future) for signposts and tooltips inside: datagrid; modal; card; accordion; stack-view; wizard
Popovers get clipped in some containers, usually the ones that have internal scrolling.
Issue Number: Multiple issues in the old repository.
No clipping confirmed for signposts and tooltips inside: datagrid; modal; card; accordion; stack-view; wizard
NOTE: this fix only works for the Angular version of the tooltips. The CSS version is still getting clipped.
> fix: overlay clipping issues

- projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
dont fall back to Core's min-height value when not using css tokens
closes #138
The base size in core changed in v6, when not using the core tokens. While the ng css has a height/width set, it did not have a min-height and min-width, which was resulting in larger than expected icons in the vertical nav
Issue Number: #138 
Sets a min-height and min-width on the nav-icon to properly size the icon. Core will be addressed separately
> fix(vertical-nav): set min-height of nav icon

- projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
dont fall back to Core's min-height value when not using css tokens
closes #138
The base size in core changed in v6, when not using the core tokens. While the ng css has a height/width set, it did not have a min-height and min-width, which was resulting in larger than expected icons in the vertical nav
Issue Number: #138 
Sets a min-height and min-width on the nav-icon to properly size the icon. Core will be addressed separately
> fix(vertical-nav): set min-height of nav icon (backport)

- projects/demo/src/app/cds-theme-select.component.ts
This fixes a regression I introduced in e87ee8b26801c275bcd1eb3d482c0a7a3c12678c.
If you hard-land on demo.example.com/path, the demo landing page is loaded instead of the page you specified.
If you hard-land on demo.example.com/path, the page you specified is loaded.
> chore: preserve path when hard landing on demo app url

- .github/workflows/demo.yml
This fixes a mistake I made in 6741ea51f55365f3576e787e861baa270d84836d.
The code needs to be checked out so the .nvmrc file is present.
> chore: add checkout step back to `demo` workflow

- package-lock.json
- package.json
This is a backport of #175.
This change allows a developer to start the demo app from a clean working directory and also rebuilds when components are changed.
If you have a clean working directory and run `npm install && npm start`, you will get build errors because the library is not built.
If you have a clean working directory and run `npm install && npm start`, it will work and changes to components will be reflected in the demo app.
No.
> chore: build library and watch for changes when starting demo app (backport)

- .github/workflows/pr-build.yml
If a build is running when changes are pushed to a PR, a new build is started and the previous build continues.
If a build is running when changes are pushed to a PR, a new build is started and the previous build should be canceled.
> chore: cancel running builds if changes are pushed

- .github/workflows/pr-build.yml
This is a backport of #213.
If a build is running when changes are pushed to a PR, a new build is started and the previous build continues.
If a build is running when changes are pushed to a PR, a new build is started and the previous build should be canceled.
> chore: cancel running builds if changes are pushed (backport)

- .github/workflows/pr-comment-bot.yml
- .github/workflows/pr-preview.yml
- .github/workflows/pr-visual-regression.yml
The Chromatic checks are skipped for PRs that target `main`.
The Chromatic checks are not skipped for PRs that target `main`.
No
This fixes the "PR Visual Regression" workflow for PRs that target the `main` branch. I broke it in #220 because I used output that didn't exist in the older version of this action.
> chore: update `potiuk/get-workflow-origin` action to v1_3

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-row.html
- projects/angular/src/data/datagrid/datagrid-row.ts
- projects/angular/src/data/datagrid/datagrid.spec.ts
- projects/angular/src/data/datagrid/datagrid.ts
- projects/angular/src/data/datagrid/providers/selection.ts
With multi-selection enabled, items can be selected one by one only.
You can use Shift key to select items in a range.
It only works for the same page, you can't select ranges starting on one page and continuing on the next.
Keyboard only selection also works.
> feat(datagrid): range selection with shift key

- projects/angular/src/data/data.module.ts
- projects/angular/src/data/datagrid/datagrid.module.ts
- projects/angular/src/emphasis/emphasis.module.ts
- projects/angular/src/forms/checkbox/checkbox.module.ts
- projects/angular/src/forms/common/common.module.ts
- projects/angular/src/forms/common/common.spec.ts
- projects/angular/src/forms/common/wrapped-control.spec.ts
- projects/angular/src/forms/datepicker/datepicker.module.ts
- projects/angular/src/forms/input/input.module.ts
- projects/angular/src/forms/password/password.module.ts
- projects/angular/src/forms/radio/radio.module.ts
- projects/angular/src/forms/range/range.module.ts
- projects/angular/src/forms/select/select.module.ts
- projects/angular/src/forms/textarea/textarea.module.ts
- projects/angular/src/icon/icon.module.ts
- projects/angular/src/layout/layout.module.ts
- projects/angular/src/popover/popover.module.ts
- projects/angular/src/utils/conditional/conditional.module.ts
- projects/angular/src/utils/drag-and-drop/drag-and-drop.module.ts
- projects/angular/src/utils/host-wrapping/host-wrapping.module.ts
- projects/angular/src/utils/host-wrapping/host-wrapping.spec.ts
- projects/angular/src/utils/loading/loading.module.ts
- projects/angular/src/utils/outside-click/outside-click.module.ts
- projects/angular/src/utils/template-ref/template-ref.module.ts
- projects/angular/src/utils/virtual-scroll/virtual-scroll.module.ts
- projects/demo/src/app/_utils/utils.module.ts
- projects/demo/src/app/images/images.demo.module.ts
Entry components do not to be specified for libraries built with Ivy.
> chore: remove unnecessary/deprecated `entryComponents` properties

- projects/angular/src/accordion/stepper/stepper.spec.ts
- projects/angular/src/accordion/stepper/stepper.ts
closes #191
This is a backport of #232.
Bugfix
Issue Number: #191
The stepper resets when the form is reset but not when the form is patched.
No. (Unless some user is relying on the broken behavior.)
> fix(stepper): reset when form is reset but not when form is patched (backport)

- .github/workflows/pr-visual-regression.yml
This is mainly needed to fetch commits that live in another repo (forks).
Chromatic cannot find the correct baseline for commits that live in another repo.
Chromatic should find the correct baseline for commits that live in another repo.
No
> chore: fetch commit in pr visual regression workflow

- projects/angular/src/wizard/_wizard.clarity.scss
fixes #107
There's a weird vertical scroll bar in the wizard on a div that is way too tall
Issue Number: #107
use flex-grow to make the div take up the full height instead of the previous attempted fix min-height 70vh
demo here: https://251--storybook-clarity-design.netlify.app/demo/wizard/basic
> fix(wizard): remove unnecessary vertical scroll bar

- projects/angular/src/wizard/_wizard.clarity.scss
fixes  #107
Issue Number: #107 
Certain elements with special positioning logic are not always expanding the wizard content div to take up the whole available space - the div is now respecting flex-grow by setting display:flex on the parent.
> fix(wizard): fix wizard content height issues

- projects/angular/src/forms/combobox/_combobox.clarity.scss
- wrap min in calc in _combobox.clarity.scss in order to force compiler to use the css min function, instead of sass min
Close: #257
Signed-off-by: Alex Pavlov <alex.pavlov@code-pine.com>
Issue Number: #257 
Css min function is forced to be used instead of the sass min function and therefore the app compiles properly.
>     fix(combobox): force usage of css min function

- projects/angular/clarity.api.md
- projects/angular/src/forms/datepicker/day.spec.ts
- projects/angular/src/forms/datepicker/day.ts
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
fixes VPAT-3637
PR Type
Feature - Accessibility
What is the current behavior?
The currently selected date is not indicated to screen reader users. 
What is the new behavior?
The aria-label of the day is now showing the word "Selected".
Does this PR introduce a breaking change?
No.
> feat(datepicker): indicate selected day in aria label

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-page-size.spec.ts
- projects/angular/src/data/datagrid/datagrid-page-size.ts
This originated in #255 as an external contribution by @pradoslavVM. I accidentally closed that PR by running a bad `git` command.
PR Type
Fix - Accessibility
What is the current behavior?
Currently you cant set an Id for the select
displaying the page size.
What is the new behavior?
Will be able to set an Id to the select
and associate it with a label using the
for attribute.
Does this PR introduce a breaking change?
No.
> feat(datagrid): add input for page size select element id

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-page-size.spec.ts
- projects/angular/src/data/datagrid/datagrid-page-size.ts
This is backport of #270.
This originated in #255 as an external contribution by @pradoslavVM. I accidentally closed that PR by running a bad `git` command.
PR Type
Fix - Accessibility
What is the current behavior?
Currently you cant set an Id for the select
displaying the page size.
What is the new behavior?
Will be able to set an Id to the select
and associate it with a label using the
for attribute.
Does this PR introduce a breaking change?
No.
- [n/a] If applicable, have a visual design approval
Feature
No
> feat(datagrid): add input for page size select element id (v12 backport)

- .storybook/helpers/setup-storybook.helpers.ts
- .storybook/stories/checkbox-toggle/checkbox-toggle-container.stories.ts
- .storybook/stories/checkbox-toggle/checkbox-toggle.stories.ts
Documentation content changes (Storybook)
- The disabled state doesn't work and is not included in the variants
- The checkbox and checkbox container are in one story.
- The disabled state works and is included in the variants.
- The checkbox and checkbox container are in separate stories.
No
> chore: include disabled state in checkbox in story variants and split checkbox container to separate story

- projects/angular/src/data/datagrid/all.spec.ts
- projects/angular/src/data/datagrid/built-in/filters/datagrid-property-numeric-filter.spec.ts
- projects/angular/src/data/datagrid/built-in/filters/datagrid-property-numeric-filter.ts
This is a backport of #283.
This fixes the behavior of `DatagridPropertyNumericFilter` and the corresponding tests.
Currently the tests in `datagrid-property-numeric-filter.spec.ts` are not executed. 
The tests are now executed and the handling of `undefined` and non-number values was adopted to make the tests pass.
> fix(datagrid): reject undefined and strings (when active) in the numeric property filter (v12 backport)

- projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
closes #293
This is a backport of #294.
Bugfix
Issue Number: #293
The icon and text does shift when a link is selected.
No
> fix(vertical-nav): align icon and text of selected link with other links (v12 backport)

- .github/workflows/accept-merged-visual-changed.yml
When a PR is rebased and merged, the SHA of the commit that lands in the base branch is different than the SHA of the commit in the PR. This makes Chromatic report the same visual change in subsequent PRs because it uses the incorrect baseline build.
I think we can remove this once we get the Chromatic GitHub app approved since Chromatic should be able to track baselines properly. But this workaround should work until then.
> chore: auto accept merged visual changes

- .storybook/helpers/elements.data.ts
- projects/angular/src/data/datagrid/_datagrid.clarity.scss
Issue Number: https://github.com/vmware/clarity/issues/6429
The detail-pane doesn't overlap the content of the datagrid table anymore when datagrid is in a smaller container.
FYI: VMC uses this approach for mostly a month and clients seems to not have issues with it anymore.
> fix(datagrid): detail-pane overlaping the content in smaller container

- projects/angular/src/forms/checkbox/checkbox-container.ts
- projects/angular/src/forms/combobox/combobox-container.ts
- projects/angular/src/forms/common/control-container.ts
- projects/angular/src/forms/datalist/datalist-container.ts
- projects/angular/src/forms/datepicker/date-container.ts
- projects/angular/src/forms/input/input-container.ts
- projects/angular/src/forms/password/password-container.ts
- projects/angular/src/forms/radio/radio-container.ts
- projects/angular/src/forms/range/range-container.ts
- projects/angular/src/forms/select/select-container.ts
- projects/angular/src/forms/styles/_containers.clarity.scss
- projects/angular/src/forms/styles/containers.spec.ts
- projects/angular/src/forms/textarea/textarea-container.ts
- projects/demo/src/app/checkboxes/checkboxes.demo.html
- projects/demo/src/app/forms/controls/checkbox.html
- projects/demo/src/app/forms/controls/file.html
- projects/demo/src/app/forms/controls/radio.html
- projects/demo/src/app/forms/controls/select.html
- projects/demo/src/app/forms/controls/text.html
- projects/demo/src/app/forms/controls/textarea.html
- projects/demo/src/app/forms/input-group/input-group.html
- projects/demo/src/app/forms/layout/layout.html
- projects/demo/src/app/radios/radios.demo.html
- projects/demo/src/app/selects/selects.demo.html
- projects/demo/src/app/textarea/textarea.demo.html
- projects/demo/src/app/toggles/toggles.demo.html
closes #305
supersedes #308
This is a backport of #311.
Bugfix
Issue Number: #305
The validation icon and text are the same color.
No.
> fix: ensure validation icons are the correct color (backport)

- projects/angular/src/wizard/wizard-stepnav-item.spec.ts
- projects/angular/src/wizard/wizard-stepnav-item.ts
partially fixes VPAT-805 (other issues are in datagrid filters)
Bugfix
The `aria-controls` attribute on the wizard stepnav item was the stepnav item id instead of the wizard page id.
The `aria-controls` attribute on the wizard stepnav item is the wizard page id.
No
> fix: set wizard stepnav item `aria-controls` attribute to wizard page id

- projects/angular/src/wizard/wizard-stepnav-item.spec.ts
- projects/angular/src/wizard/wizard-stepnav-item.ts
This is a backport of #317.
partially fixes VPAT-805 (other issues are in datagrid filters)
Bugfix
The `aria-controls` attribute on the wizard stepnav item was the stepnav item id instead of the wizard page id.
The `aria-controls` attribute on the wizard stepnav item is the wizard page id.
No
> fix: set wizard stepnav item `aria-controls` attribute to wizard page id (v12 backport)

- package.json
The `sass` CLI does not automatically watch imported paths, so explicitly instructing `sass` to watch the projects folder fixes the issue.
> chore: apply style changes in storybook watch mode

- projects/angular/src/typography/_lists.scss
screen readers can't read list-style-type: none, so change the markers to be transparent instead
Fixes VPAT-612
Screen readers cannot read list-style-type: none
Issue Number: VPAT-612
The markers needed to be hidden in a different way, using color: transparent, with no margin/padding. list-style-position:outside allows the 0 margin/padding to work
> fix(list): make unstyled list markers transparent instead of list-style-type none

- projects/angular/src/typography/_lists.scss
> fix(list): make unstyled list markers transparent instead of list-sytle-type none (backport)

- projects/angular/src/data/stack-view/stack-block.ts
Bugfix
VPAT-636: "When I press space on the live website the page scrolls down in addition to the expanding/collapsing. This should work like the accordion component." -- comment by Amy Li
The space key toggles the stack block without scrolling the page.
No.
> fix(stack-view): prevent page scroll when block toggled via space key

- projects/angular/src/forms/common/wrapped-control.spec.ts
- projects/angular/src/forms/common/wrapped-control.ts
- projects/angular/src/forms/input/input.spec.ts
This was a bug fix for old issue with input type=number that is not reproducible anymore. It causes extra valueChanged events on blur after upgrade to Angular v14.
closes #337
There is an enforcement of the "touched" form status on "blur".
It causes a "valueChange" event too early in lifecycle. It's observable after upgrading to angular v14 and importing Clarity Module before FormsModule.
The order of imports should not matter!
Issue Number: 337
Enforcement removed.
> fix(forms): remove touched enforcement

- projects/angular/clarity.api.md
- projects/angular/src/forms/datepicker/all.spec.ts
- projects/angular/src/forms/datepicker/date-input.validator.spec.ts
- projects/angular/src/forms/datepicker/date-input.validator.ts
- projects/angular/src/forms/datepicker/datepicker.module.ts
- projects/angular/src/forms/datepicker/index.ts
- projects/demo/src/app/datepicker/datepicker-min-max.html
Bugfix
The datepicker control does not report errors when the entered date violates a min/max constraint.
Issue Number: VPAT-664
The datepicker control reports error when the entered date violates a min/max constraint. The input will show the error state (red underline and icon), but it is up the application to display an error message.
No.
> fix(datepicker): validate min/max date

- projects/angular/src/data/stack-view/stack-header.ts
- projects/demo/src/app/stack-view/stack-view-static.html
- vmware-clarity/website#41
Bugfix
The stack view header action buttons are in an `h4` element.
Issue Number: VPAT-827
The stack view header action buttons are not in an `h4` element.
No.
> fix(stack-view): remove action buttons from h4 element

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-filter.spec.ts
- projects/angular/src/data/datagrid/datagrid-filter.ts
- projects/angular/src/utils/i18n/common-strings.default.ts
Feature
The `aria-label` of all datagrid filter toggle buttons was "Toggle column filter".
Issue Number: VPAT-615
The `aria-label` of datagrid filter toggle buttons now contains the column name (e.g. "Toggle user filter"). This improves accessibility by providing a unique/specific `aria-label` for each filter toggle button.
No.
If your application localizes the `datagridFilterAriaLabel` string, you will need to add the `{COLUMN}` placeholder to take advantage of this feature. It will work the same as before without the placeholder, so this change is backwards compatible.
> feat(datagrid): include column title in filter toggle button aria-label

- projects/angular/clarity.api.md
- projects/angular/src/data/tree-view/tree-node-link.ts
- projects/angular/src/data/tree-view/tree-node.html
- projects/angular/src/data/tree-view/tree-node.spec.ts
- projects/angular/src/data/tree-view/tree-node.ts
Bugfix
Previously, the `aria-selected` attribute and the selected/unselected screen reader text was only set on selectable tree nodes.
Issue Number: VPAT-603
Now, the `aria-selected` attribute and selected screen reader text is also set on active tree node links so that this state is indicated to screen reader users.
No.
> fix(tree-view): announce active tree node links as selected

- projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
- projects/angular/src/layout/vertical-nav/vertical-nav-group.ts
This prevents an Angular 14 developer warning.
closes #323
Bugfix
When opening/closing a vertical nav group, the following developer warning is logged by Angular 14:
>The animation trigger "clrExpand" is attempting to animate the following not animatable properties: overflowY
Issue Number: #323
No warning. The animation is unchanged visually.
No.
> fix(vertical-nav): stop unnecessarily animating `overflow-y`

- projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.spec.ts
- projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
- projects/angular/src/forms/common/if-control-state/if-control-state.service.spec.ts
- projects/angular/src/forms/common/if-control-state/if-control-state.service.ts
- projects/angular/src/forms/common/if-control-state/if-error.spec.ts
- projects/angular/src/forms/tests/container.spec.ts
- projects/angular/src/utils/testing/helpers.spec.ts
Can be observed when FormsModule (ReactiveFormsModule) is imported after ClarityModule.
Due to the special module order requirements it can't be reproduced in tests, storybook or demo app.
This StackBlitz represents a patched version of the fix, which can be manually tested:
https://stackblitz.com/edit/input-on-blur-issue?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts
Closes #385 
Two blur events are needed to run validation. ClarityModule should be imported before ReactiveFormsModule.
Issue Number: #385
Evaluation of the validation state is postponed to next frame, so the import-dependent …
> fix(forms): form items set touched too late

- projects/angular/src/layout/nav/header.ts
This was accidentally introduced in 1ce653a4bb444395d33c6f9d8f57ebcddb98537a.
> fix(header): remove incorrect, duplicate `click` event handler

- projects/angular/src/image/_icons.clarity.scss
The icon generating scripts in SCSS were only supporting hex-colors, "white" and "black".
When HSL or other plain-text value was supplied, they failed by prepending `#` to the value.
This results in spinners being broken on our web-site.
Issue Number: #362 
The scripts can generate icons with any color syntax. Should fix website if updated.
> fix: update icon generators to support hsl and clear text color values

- projects/angular/src/data/stack-view/_stack-view.clarity.scss
Outlines are external to the element. Safari can be more restrictive to such content and will not display it.
Same as in many other places in the project, we need to reposition the outline by some negative outline-offset.
Focus outline is not visible in Safari
Issue Number: #31 
Outline is visible in Safari and Chrome.
> fix(stackview): fix focus outline in safari

- projects/angular/src/data/datagrid/datagrid-row.html
See vmware/clarity#5574 for more information.
Bugfix
Style/layout issues if a single select datagrid with row selection is inside a form.
No style/layout issues if a single select datagrid with row selection is inside a form.
No.
> fix(datagrid): prevent issues with single select radio in forms

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
Bugfix
The datagrid detail pane did not take 2/3 of the space when open. This is a regression that I introduced in #339.
Issue Number: #432
The datagrid detail pane did takes 2/3 of the space when open. Some other styles are also fixed on the parent datagrid.
No.
>  fix(datagrid): apply correct styles to parent datagrid when detail open

- projects/angular/src/layout/nav/_header.clarity.scss
- projects/angular/src/layout/nav/_links.clarity.scss
- projects/angular/src/layout/nav/_subnav.clarity.scss
- projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
- projects/angular/src/popover/dropdown/_dropdown.clarity.scss
- projects/angular/src/utils/_mixins.scss
- projects/angular/src/utils/_reboot.clarity.scss
fixes VPAT-13812, closes #352
Links don't have underlines by default, this is confusing and bad for accessibility
Issue Number: #352 
Links have underlines - except for in the nav, subnav, or vertical nav, or in dropdown menus
It's a breaking visual change
> feat(typography): add underline to links for accessibility

- projects/angular/clarity.api.md
- projects/angular/src/popover/dropdown/_menu-mixins.clarity.scss
- projects/angular/src/popover/dropdown/dropdown-item.ts
- projects/angular/src/popover/dropdown/dropdown.spec.ts
- I couldn't get enter/space key tests to work.
Bugfix
Disabled dropdown items can be activated via click, space, and enter.
Issue Number: #387 and #389
Disabled dropdown items cannot be activated via click, space, and enter.
No.
> fix(dropdown): prevent activating disabled dropdown item (and minor cleanup)

- .storybook/stories/stack-view/stack-block.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/data/stack-view/stack-block.spec.ts
- projects/angular/src/data/stack-view/stack-block.ts
- vmware-clarity/website#51
Remove dead code.
Dead inputs exist.
Dead inputs are removed.
Yes.
- The `clrStackViewSetsize` input has been removed.
- The `clrStackViewPosinset` input has been removed.
- These inputs had no effect. The functionality was previously removed.
> feat(stack-view): remove dead stack view `setsize` and `posinset` inputs 

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-column.spec.ts
- projects/angular/src/data/datagrid/datagrid-column.ts
- projects/demo/src/app/datagrid/sorting/sorting.html
- projects/demo/src/app/datagrid/sorting/sorting.ts
Remove deprecated feature.
Two, parallel sets of datagrid sorting properties exist.
Deprecated datagrid sorting properties are removed in favor of newer alternatives.
Yes. The deprecated datagrid sorting APIs are removed in favor of the newer APIs. You may need to make the following changes:
- `sortIcon`: Use `sortDirection` instead.
- `clrDgSorted`: Use `clrDgSortOrder` instead.
- `clrDgSortedChange`: Use `clrDgSortOrderChange` instead.
> feat(datagrid): remove deprecated sorting properties

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
- projects/angular/src/data/datagrid/datagrid-row-detail.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
Remove deprecated feature.
There are two sets of common strings for the same things, one of which is misspelled.
The `dategrid*` common strings are removed in favor of the `datagrid*` properties.
Yes. The misspelled `dategrid*` common strings are removed. Please rename these properties to `datagrid*`.
> feat(datagrid): remove `dategrid*` properties from `ClrCommonStrings`

- .storybook/stories/vertical-nav/vertical-nav-group.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/layout/vertical-nav/vertical-nav-group.html
- projects/angular/src/layout/vertical-nav/vertical-nav-group.spec.ts
- projects/angular/src/layout/vertical-nav/vertical-nav-group.ts
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
- projects/demo/src/app/vertical-nav/accessibility/vertical-nav-accessibility.demo.html
- projects/demo/src/app/vertical-nav/highlights/vertical-nav-highlights.demo.html
- projects/demo/src/app/vertical-nav/nested-icon-menus/vertical-nav-nested-icon-menus.demo.html
- projects/demo/src/app/vertical-nav/nested-menus/vertical-nav-nested-menus.demo.html
- projects/demo/src/app/vertical-nav/partially-nested-icon-menu/vertical-nav-partial-nested-icon-menus.demo.html
- projects/demo/src/app/vertical-nav/partially-nested-menu/vertical-nav-partial-nested-menus.demo.html
- projects/demo/src/app/vertical-nav/routing/vertical-nav-routing.demo.html
- projects/demo/src/app/vertical-nav/unstructured-routes/unstructured-routes.html
- projects/demo/src/app/vertical-nav/without-expanded-directive/without-expanded-directive.html
Bug fix
The `aria-label` on the vertical nav group toggle button was unnecessary. And it was not always unique.
Issue Number: VPAT-14152
The vertical nav group toggle button no longer has an `arial-label`.
Yes.
- The `clrVerticalNavGroupLabel` input has been removed.
- The `verticalNavGroupToggle` common string has been removed.
> feat(vertical-nav): remove `aria-label` from vertical nav group buttons

- projects/angular/src/accordion/accordion-panel.html
- projects/angular/src/accordion/stepper/stepper-panel.spec.ts
- projects/angular/src/forms/datepicker/daypicker.spec.ts
Remove feature.
Automatic aria-live announcements by the stepper for error state.
No automatic aria-live announcements by the stepper.
Yes. The stepper will no longer announce error states. Applications can use `LiveAnnouncer` from `@angular/cdk` to handle any required announcements.
> feat(stepper): remove `aria-live` announcement for error state

- projects/angular/clarity.api.md
- projects/angular/src/popover/dropdown/dropdown-item.spec.ts
- projects/angular/src/popover/dropdown/dropdown-item.ts
- The docs already explain this.
Remove deprecated feature.
The `clrDropdownItem` directive supports the `disabled` attribute. Using the `disabled` attribute on a `clrDropdownItem` that is a `button` element breaks keyboard navigation. Focus gets lost on the disabled item.
The `clrDropdownItem` directive does not support the `disabled` attribute.
Yes. Use `clrDisabled` instead of `disabled` to disable a `clrDropdownItem`.
> feat(dropdown): remove `disabled` attribute from `clrDropdownItem`

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
- projects/angular/src/data/datagrid/datagrid-pagination.ts
Pagination input changes current page on Tab, click-out, etc. blur events.
Issue Number: VPAT-784
Pagination input will only change the current page on Enter.
Blur resets the input value to the actual current page.
> fix(datagrid): pagination input should only change page on enter

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
This fixes a regression that was introduced in #302.
Bugfix
The border between the column and the detail pane does not extend to the placeholder element below the rows.
The border between the column and the detail pane extends to the placeholder element below the rows.
No.
> fix(datagrid): show full border when detail pane is open

- projects/angular/src/popover/common/abstract-popover.ts
It is common for base classes of components/directives to use the directive decorator. I think it may even be required now.
> chore: remove unnecessary annotation comment

- projects/angular/clarity.api.md
- projects/angular/src/popover/tooltip/_tooltips.clarity.scss
- projects/angular/src/popover/tooltip/all.spec.ts
- projects/angular/src/popover/tooltip/providers/tooltip-mouse.service.spec.ts
- projects/angular/src/popover/tooltip/providers/tooltip-mouse.service.ts
- projects/angular/src/popover/tooltip/tooltip-content.ts
- projects/angular/src/popover/tooltip/tooltip-trigger.spec.ts
- projects/angular/src/popover/tooltip/tooltip-trigger.ts
- projects/angular/src/popover/tooltip/tooltip.ts
Bugfix
The tooltip content was hidden as soon as the user moused out of the trigger.
Issue Number: VPAT-617
The tooltip content will stay visible if the user mouses from the trigger into the content. To support this, the tooltip content has an expanded hover target provided by the `::after` pseudo element.
No.
> fix(tooltip): keep tooltip content visible as user hovers 

- projects/angular/clarity.api.md
- projects/angular/src/forms/datepicker/date-container.ts
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
- https://github.com/vmware-clarity/website/pull/58
Remove unnecessary code.
The `datepickerToggle` exists and is only used as a fallback.
The `datepickerToggleChooseDateLabel` and `datepickerToggleChangeDateLabel` strings should be used instead.
Yes. The `datepickerToggle` common string property was removed. Use `datepickerToggleChooseDateLabel` and `datepickerToggleChangeDateLabel` instead.
> feat: remove `datepickerToggle` fallback common string property

- projects/angular/clarity.api.md
- projects/angular/src/data/tree-view/_tree-view.clarity.scss
- projects/angular/src/data/tree-view/tree-node.html
- projects/angular/src/data/tree-view/tree-node.ts
Bugfix
The tree node content is not a label for the checkbox; therefore, it is not included in the checkbox's click target.
Issue Number: VPAT-791
The tree node content is rendered in the checkbox's label; therefore, it is included in the checkbox's click target.
Technically, yes. The internal DOM structure of the tree node component has been changed. The `.clr-treenode-content` element is no longer rendered for selectable tree nodes; instead, the tree node content is rendered inside the checkbox's label element.
> fix(tree-view): associate tree node content with checkbox as label

- projects/angular/src/modal/modal.html
Bugfix
- Focus was not captured on a focusable element inside the modal upon open.
- Focus was not returned to the previous focused element upon close of a modal.
- Focus is captured on a focusable element inside the modal upon open.
- Focus is returned to the previous focused element upon close of a modal.
This change contributes to fixing VPAT-735.
No.
> fix(modal): capture and return focus

- projects/angular/src/utils/_overwrites.clarity.scss
- projects/angular/src/utils/_theme.dark.clarity.scss
This fixes mistakes I made in #368.
Bugfix
Some wizard sidenav scss variables were missing.
The missing wizard sidenav scss variables are restored.
No.
> fix(wizard): restore wizard sidenav scss variables

- projects/angular/src/modal/modal.html
This fixes a regression I introduced in #431.
Bugfix
The content behind the modal would be scrolled when the user tabs through the modal.
The content behind the modal is not scrolled when the user tabs through the modal.
No.
> fix(modal): prevent scrolling content under modal when tabbing

- projects/angular/clarity.api.md
- projects/angular/src/modal/modal.html
- projects/angular/src/modal/modal.module.ts
- projects/angular/src/modal/modal.spec.ts
- projects/angular/src/wizard/wizard.spec.ts
This fixes a regression I introduced in #455.
Bugfix
The modal close button was focused on modal open instead of the title. This was a regression that I introduced in #455.
This modal title is focused on modal open.
Yes. The `ModalModule` no longer exports `ClrFocusOnViewInitModule`.
> fix(modal): focus modal title when modal opened

- projects/angular/clarity.api.md
- projects/angular/src/layout/tabs/tabs.ts
closes: #451
aria-owns is not needed when dom structure conveys the correct order. it was leading to issues with screen readers when some tabs were conditionally rendered.
Screen reader will report tabs in wrong order, because of the messed up aria-owns. Reproducible in Chrome.
Issue Number: #451 
Tabs are read in the correct order
> fix(tabs): ensure tabs are announced in the correct order

- .storybook/helpers/setup-storybook.helpers.ts
- .storybook/stories/datagrid/modal-stacked-on-detail.stories.ts
- .storybook/stories/datagrid/nested-detail-in-detail.stories.ts
- .storybook/stories/datagrid/nested-popover-in-detail.stories.ts
- .storybook/stories/modal/nested-datagrid-detail.stories.ts
- .storybook/stories/modal/nested-popover.stories.ts
- .storybook/stories/modal/stacked-modal.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/button/button-group/button-group.ts
- projects/angular/src/data/datagrid/datagrid-action-overflow.ts
- projects/angular/src/data/datagrid/datagrid-column-toggle.ts
- projects/angular/src/data/datagrid/datagrid-column.ts
- projects/angular/src/data/datagrid/datagrid-detail.ts
- projects/angular/src/data/datagrid/providers/detail.service.spec.ts
- projects/angular/src/data/datagrid/providers/detail.service.ts
- projects/angular/src/forms/combobox/combobox.ts
- projects/angular/src/forms/datepicker/date-container.ts
- projects/angular/src/layout/tabs/tabs.ts
- projects/angular/src/modal/modal-stack.service.spec.ts
- projects/angular/src/modal/modal-stack.service.ts
- projects/angular/src/modal/modal.ts
- projects/angular/src/popover/dropdown/dropdown.ts
- projects/angular/src/popover/signpost/signpost.ts
- projects/angular/src/popover/tooltip/tooltip.ts
- projects/angular/src/utils/popover/all.spec.ts
- projects/angular/src/utils/popover/popover-host.directive.ts
- projects/angular/src/utils/popover/stop-escape-propagation.directive.spec.ts
- projects/angular/src/utils/popover/stop-escape-propagation.directive.ts
- projects/demo/src/app/popovers/dummy-anchor.ts
Bugfix
Pressing escape closed all open popovers, modals, and detail panes.
Issue Number: #314, VPAT-735
Pressing escape closes only the last-opened popover, modal, or detail pane.
Yes.
> fix: close only last-opened popover/modal/detail pane when escape key is pressed 

- projects/angular/src/forms/datepicker/date-container.ts
closes #310
Bugfix
On mobile, the native datepicker is used, so the toggle button is not present. This causes errors when the code attempts to update the toggle button's `title` and `aria-label` attributes.
Issue Number: #310
This fix simply skips updating the toggle button's attributes when it is not present.
No.
> fix(datepicker): skip updating toggle button attributes when disabled

- projects/angular/src/utils/variables/_variables.typography.scss
Remove deprecated thing.
Yes. The unused `$clr-monoFont` scss variable has been removed.
> feat: remove deprecated, unused `$clr-monoFont` scss variable

- projects/angular/src/utils/popover/stop-escape-propagation.directive.ts
Bugfix
Unit test error reported by a user:
```
TypeError: Cannot read properties of undefined (reading 'unsubscribe')
at StopEscapePropagationDirective.call [as ngOnDestroy] (node_modules/@clr/angular/fesm2020/clr-angular.mjs:2620:27)
at executeOnDestroys (node_modules/@angular/core/fesm2020/core.mjs:6031:32)
at cleanUpView (node_modules/@angular/core/fesm2020/core.mjs:5941:9)
at destroyViewTree (node_modules/@angular/core/fesm2020/core.mjs:5774:17)
```
I am not sure how this is possible. The `ngOnDestroy` method is apparently sometimes called without `ngOnInit` having been called first. I think this …
> fix: prevent error on destroy in `StopEscapePropagationDirective`

- projects/angular/src/forms/combobox/combobox.ts
- projects/angular/src/forms/combobox/option-items.directive.spec.ts
- projects/angular/src/forms/combobox/option-items.directive.ts
- projects/angular/src/forms/combobox/providers/option-selection.service.ts
closes: #386
BREAKING CHANGE: the combobox list is no longer prefiltered on first dialog open, but shows all options.
When the combobox has a preselection, it shows filtered list on first open.
Issue Number: #386
It shows full list on first open, and filters only after input in the search field.
It's a behavioral change, no API is broken, so no migration is needed.
> fix(combobox): do not prefilter when first opened

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
- projects/angular/src/data/datagrid/_properties.datagrid.scss
- projects/angular/src/data/datagrid/_variables.datagrid.scss
- projects/angular/src/utils/_overwrites.clarity.scss
- projects/angular/src/utils/_theme.dark.clarity.scss
- projects/ui/src/shim.cds-core.scss
Breaking API renames
Two CSS custom property names were missing "color" suffix.
Renamed CSS custom properties to have "color" suffix.
Yes. See commit message.
> feat(datagrid): rename css custom properties to add "color" suffix

- projects/demo/src/app/app.component.html
- projects/demo/src/app/app.component.ts
- projects/demo/src/environments/environment.prod.ts
- projects/demo/src/environments/environment.ts
The @cds/core shim does not work with the @clr/ui dark theme since it does not use CSS custom properties.
Demo app change.
The @cds/core theme selector is present in the @clr/ui dark theme demo app, but it doesn't work.
The @cds/core theme selector is not present in the @clr/ui dark theme demo app.
No.
> chore: remove @cds/core theme selector in @clr/ui dark theme demo app

- .storybook/pages/cds-core-shim.stories.mdx
This fixes a mistake I main in #486.
> chore: use correct path for @cds/core shim in storybook page

- projects/angular/src/layout/vertical-nav/vertical-nav-link.ts
- projects/angular/src/layout/vertical-nav/vertical-nav.html
This reverts commit part of #480.
Adding `role="listitem"` to `a` element overrides the link role.
> Revert "fix(vertical-nav): add aria list structure to vertical nav links"

- projects/angular/src/forms/common/if-control-state/if-control-state.service.ts
- projects/angular/src/forms/datepicker/date-input.validator.spec.ts
closes #476
The "touched" control check was nice to have but not required for the proper validation operation. Also, the event order is not stable in different Angular versions and orders of module imports. The setTimeout() was trying to ensure the correct order. But it leads to regressions with OnPush components. This fix removes the setTimeout at the expense of sacrificing the "touched" check.
This fix is the final step of a chain of regressions that came with an Angular 14 update. The last regression was causing form elements in OnPush components to validate on the second `blur` event, skipping the first one.
Issue Number: #476 
Form …
> fix(forms): update validation with onpush strategy components

- .storybook/helpers/setup-storybook.helpers.ts
- .storybook/manager.js
- .storybook/public/manager.css
- package-lock.json
- package.json
Chromatic check prevents themed variants from being added to the build.
Chromatic check is skipped, since it changes the webpack stats output which is used by chromatic to be smart about what to test. This also fixes a small bug added in v15 where the manager.css file wasn't being loaded properly due to a change to leverage raw-loader (which isn't required by the manager webpack) and expands the css in the manager file to hide all variants in the UI.
> chore: remove chromatic check for accurate webpack stats tracking

- package.json
I missed this in #486.
The `shim.cds-core.min.css` is not in the `@clr/ui` package.
The `shim.cds-core.min.css` is in the `@clr/ui` package.
No.
> fix: include minified cds-core shim in `@clr/ui` package

- package.json
I missed this in #486.
This is a backport of #517 to 13.x
The `shim.cds-core.min.css` is not in the `@clr/ui` package.
The `shim.cds-core.min.css` is in the `@clr/ui` package.
No.
> fix: include minified cds-core shim in `@clr/ui` package (13.x backbort)

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
Bugfix
The "hand" cursor is used when hovering the selection cell when selection is disabled.
The "not allowed" cursor is used when hovering the selection cell when selection is disabled.
No.
This fixes a mistake I made in #478.
> fix(datagrid): show "not allowed" cursor in disabled selection cell

- projects/angular/src/data/datagrid/datagrid-row.html
- projects/angular/src/data/datagrid/datagrid-row.spec.ts
Bugfix
Setting `[clrDgSelectable]="false"` does not disable the checkbox/radio button.
Issue Number: #520
Setting `[clrDgSelectable]="false"` disables the checkbox/radio button.
No.
This is a workaround for a regression that was introduced in Angular v15. See angular/angular#48350 for details.
> fix(datagrid): disable row checkbox/radio button in Angular v15

- .storybook/stories/datagrid/datagrid-action-overflow.stories.ts
- .storybook/stories/datagrid/datagrid.stories.ts
- projects/angular/src/data/datagrid/_datagrid.clarity.scss
- projects/ui/src/shim.cds-core.scss
The manage columns button in the core light and dark theme is incorrect. 
The datagrid action overflow popover selected/hover background color is incorrect
Buttons throughout the library are incorrectly receiving a filter. 
Issue Number: #508 
Maps the colors of the manage columns button to the correct core design tokens. 
Fixes the datagrid action overflow popover background color by mapping it to the correct value.
Adds the focus state to the manage columns button (to align with the active state).
Removes unexpected filter on all btn elements based on state.
> fix(datagrid): resolve manage columns and popover shim color issues

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
This is a backport of #522 to 13.x
Bugfix
The "hand" cursor is used when hovering the selection cell when selection is disabled.
The "not allowed" cursor is used when hovering the selection cell when selection is disabled.
No.
This fixes a mistake I made in #478.
> fix(datagrid): show "not allowed" cursor in disabled selection cell (13.x backport)

- projects/angular/src/data/datagrid/datagrid-row.html
- projects/angular/src/data/datagrid/datagrid-row.spec.ts
This is a backport of #521 to 13.x.
Bugfix
Setting `[clrDgSelectable]="false"` does not disable the checkbox/radio **button in Angular v15.**
Issue Number: #520
Setting `[clrDgSelectable]="false"` disables the checkbox/radio button in Angular v15.
No.
This is a workaround for a regression that was introduced in Angular v15. See angular/angular#48350 for details.
> fix(datagrid): disable row checkbox/radio button in Angular v15 (13.x backport)

- .storybook/stories/datagrid/datagrid-action-overflow.stories.ts
- .storybook/stories/datagrid/datagrid.stories.ts
- projects/angular/src/data/datagrid/_datagrid.clarity.scss
- projects/ui/src/shim.cds-core.scss
The manage columns button in the core light and dark theme is incorrect. 
The datagrid action overflow popover selected/hover background color is incorrect
Buttons throughout the library are incorrectly receiving a filter. 
Issue Number: #508 
Maps the colors of the manage columns button to the correct core design tokens. 
Fixes the datagrid action overflow popover background color by mapping it to the correct value.
Adds the focus state to the manage columns button (to align with the active state).
Removes unexpected filter on all btn elements based on state.
> fix(datagrid): resolve manage columns and popover shim color issues (backport to 13.x)

- .github/workflows/release-preview.yml
- .github/workflows/release.yml
This step is no longer needed since v15 `beta`/`rc` is now on `main`.
> chore: remove "check if main is merged" step from release workflows

- .storybook/stories/datagrid/datagrid-row.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-row.spec.ts
- projects/angular/src/data/datagrid/datagrid-row.ts
Currently, when using a multi selectable datagrid, the rows do not render in their correct state (based on clrDgSelectable). Since the clrDgSelectable and item values are both Inputs, the clrDgSelectable state may be set within the component prior to the item, which results in the selectable state being lost. This change introduces a private local variable to keep track of the clrDgSelectable state, and introduces a setter for the item that sets the value when item is available. 
Issue Number: #157 
When rendering a multi-select datagrid, rows will properly respect the clrDgSelectable input when initially rendered. 
- [ x] No
> fix(datagrid): set non-selectable multi select rows to disabled on initial render

- projects/angular/src/forms/datepicker/daypicker.html
The next month icon within the button does not use the title attribute, but other icons within the datepicker use the title attribute to match the aria-label text. 
Issue Number: #450 
Adds the title attribute to the next month icon to align with other icon usage within the component and library. 
- [ x] No
> fix(datepicker): add title to next month icon to align with other icons

- .storybook/stories/button/button.stories.ts
- projects/angular/src/button/_buttons.clarity.scss
- projects/angular/src/button/_variables.buttons.scss
- projects/angular/src/utils/_theme.dark.clarity.scss
Missing dark theme styles and inconsistent application of warning button styles
Issue Number: #425 
Follows the existing pattern for adding the warning color, and appropriate overrides. Updates the story to hide controls for flat button types (since they don't have the same states as other buttons).
> fix(button): add mapping of warning button to danger styles

- .storybook/stories/button/button.stories.ts
- projects/angular/src/button/_buttons.clarity.scss
- projects/angular/src/button/_variables.buttons.scss
- projects/angular/src/utils/_theme.dark.clarity.scss
Missing dark theme styles and inconsistent application of warning button styles
Issue Number: #425 
Follows the existing pattern for adding the warning color, and appropriate overrides. Updates the story to hide controls for flat button types (since they don't have the same states as other buttons).
> fix(button): add mapping of warning button to danger styles (backport)

- projects/angular/src/forms/datepicker/daypicker.html
The next month icon within the button does not use the title attribute, but other icons within the datepicker use the title attribute to match the aria-label text. 
Issue Number: #450 
Adds the title attribute to the next month icon to align with other icon usage within the component and library. 
- [ x] No
> fix(datepicker): add title to next month icon to align with other icons (backport)

- .storybook/stories/datagrid/datagrid-row.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-row.spec.ts
- projects/angular/src/data/datagrid/datagrid-row.ts
Currently, when using a multi selectable datagrid, the rows do not render in their correct state (based on clrDgSelectable). Since the clrDgSelectable and item values are both Inputs, the clrDgSelectable state may be set within the component prior to the item, which results in the selectable state being lost. This change introduces a private local variable to keep track of the clrDgSelectable state, and introduces a setter for the item that sets the value when item is available. 
Issue Number: #157 
When rendering a multi-select datagrid, rows will properly respect the clrDgSelectable input when initially rendered. 
- [ x] No
> fix(datagrid): set non-selectable multi select rows to disabled on initial render (backport)

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-column-toggle-trackby.ts
- projects/angular/src/data/datagrid/datagrid-column-toggle.ts
- projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
- projects/angular/src/data/datagrid/datagrid-items-trackby.ts
closes #475
closes #503
Bugfix
Clicking the "manage columns" button will make unselectable rows selectable.
Issue Number: #475 and #503
Clicking the "manage columns" button will not make unselectable rows selectable
No.
This is a workaround to prevent the items `trackBy` function from being replaced when the "manage columns" button is clicked. This is not a complete solution. If there is another `ngForTrackBy` function within the datagrid in application code, it could sill replace the items `trackBy` function whether it is the row iterator or not.
> fix(datagrid): prevent "manage columns" from making rows selectable

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-column-toggle-trackby.ts
- projects/angular/src/data/datagrid/datagrid-column-toggle.ts
- projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
- projects/angular/src/data/datagrid/datagrid-items-trackby.ts
This is a backport of #538 to 13.x.
closes #475
closes #503
Bugfix
Clicking the "manage columns" button will make unselectable rows selectable.
Issue Number: #475 and #503
Clicking the "manage columns" button will not make unselectable rows selectable
No.
This is a workaround to prevent the items `trackBy` function from being replaced when the "manage columns" button is clicked. This is not a complete solution. If there is another `ngForTrackBy` function within the datagrid in application code, it could sill replace the items `trackBy` function whether it is the row iterator or not.
> fix(datagrid): prevent "manage columns" from making rows selectable (13.x backport)

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
- projects/angular/src/data/datagrid/datagrid-items-trackby.ts
- projects/angular/src/data/datagrid/datagrid-items.spec.ts
- projects/angular/src/data/datagrid/datagrid-items.ts
- projects/angular/src/data/datagrid/datagrid-row.spec.ts
- projects/angular/src/data/datagrid/datagrid.spec.ts
- projects/angular/src/data/datagrid/datagrid.ts
- projects/angular/src/data/datagrid/index.ts
- projects/angular/src/data/datagrid/providers/items.ts
- projects/angular/src/data/datagrid/providers/selection.spec.ts
- projects/angular/src/data/datagrid/providers/selection.ts
This is a backport of #539 to 13.x.
closes #157
- I will open a website PR.
Bugfix
You cannot use `[clrDgSelectable]` with `*ngFor` due to use of the iterator `trackBy` function to track selection.
It is impossible (or very difficult) to grab the correct `trackBy` function via the row iterator structural directive. The `ngForTrackBy` directive would grab the `trackBy` function from any `*ngFor` in the datagrid, not just the row iterator.
Further, needing the item index to track selection introduces a race condition when `*ngFor` is used. We don't have the collection of items when the rows inputs are set, so `clrDgSelectable` doesn't work.
Issue Number: #157
The fix is to pass a "track by" function directly to the datagrid. This change …
> fix(datagrid): add workaround to enable `clrDgSelectable` with `*ngFor` (13.x backport)

- .storybook/stories/datagrid/datagrid-column.stories.ts
I missed this in 6af3832fe6b4e0ea7acd225cb3b0a1db2587231b.
Storybook fix
> chore(datagrid): remove old sorting bindings from column story

- .storybook/stories/datagrid/datagrid-column.stories.ts
> chore(datagrid): remove unused sort event handler in column story

- .storybook/stories/datagrid/datagrid-column.stories.ts
- vmware-clarity/website#85
Storybook change
The `clrDgColumnResize` event is not in the datagrid column story.
The `clrDgColumnResize` event is in the datagrid column story.
No.
> chore(datagrid): add `clrDgColumnResize` event to column story

- projects/angular/src/forms/combobox/_properties.combobox.scss
The css variable is incorrect, causing the styles to be applied via the fallback but not allowing for changes via the css variable. 
The css variable is using the correct name to align with our lookup functionality.
> fix(combobox): rename incorrect css var (missing -color)

- projects/angular/src/forms/combobox/_properties.combobox.scss
Porting of #544 to 13.x branch
> fix(combobox): rename incorrect css var (missing -color) (backport 13.x)

- .github/workflows/accept-merged-visual-changes.yml
- .github/workflows/pr-visual-regression.yml
- .storybook/preview.js
- package.json
Reviving this change to import our scss files directly. Ideally, chromatic will now detect changes to scss files and trigger a full rebuild on any/all scss changes in the library. This also removes the --externals for package-lock, as this behavior *should* be trigger by chromatic.
> chore: import scss files directly for chromatic to detect changes

- .storybook/stories/forms/forms-reactive.stories.ts
- .storybook/stories/forms/forms-template-driven.stories.ts
- projects/angular/src/forms/common/abstract-container.ts
- projects/angular/src/forms/datepicker/date-container.spec.ts
- projects/angular/src/forms/tests/container.spec.ts
- projects/demo/src/app/forms/forms.demo.module.ts
- projects/demo/src/app/forms/forms.demo.routing.ts
- projects/demo/src/app/forms/forms.demo.ts
- projects/demo/src/app/forms/reactive/reactive.ts
- projects/demo/src/app/forms/template-driven/template-driven.ts
Forms validation regressed multiple times, after certain Angular update, after which the order of imports of Angular's FormsModule and ClarityModule started to matter for the order of receiving `touched` event and angular validation status event.
Previously, we were trying to augment our internal validity state, based on whether `touched` had arrived or not. With the race condition described above, this was causing different side effects, depending on the fix attempted, including:
- form elements only got validated on the second `blur`
- form elements got validated immediately, when page was opened
Additional problem was that `touched` changes do not have an event handler in the …
> fix(forms): fix template-driven forms validation regression

- .storybook/stories/datagrid/datagrid-column.stories.ts
This is a backport of c6603dfbda263a04d25b2d08504ce33dca1481aa (#546) to 13.x.
> chore(datagrid): add `clrDgColumnResize` event to column story (backport to 13.x)

- projects/angular/src/popover/tooltip/_tooltips.clarity.scss
When a tooltip trigger is hovered, there is a tiny chance that the `::before` pseudo-element of the tooltip content will pop up under the mouse pointer and cause the tooltip trigger to no longer be hovered and the tooltip content (with its `::before` pseudo-element) to disappear. Then the mouse pointer hovers over the tooltip trigger again, and the tooltip content pops up, and this cycle repeats, causing the tooltip content to flash cyclically.
With this fix, no matter where the mouse pointer hovers over the tooltip trigger, once the tooltip content appears, its `::before` pseudo-element will not be the target of pointer events, so the tooltip trigger's hover state will not change.
This is a backport of 98a5ec9080e71e420cc923abd64246e2e0505fe4 (#560) to 13.x.
> fix(tooltip): prevent flashing when hovering trigger (backport to 13.x)

- package-lock.json
- package.json
Updates angular (which updates webpack) and commitizen (which updates minimist)
> chore: update angular/commitizen to resolve security warnings

- .storybook/stories/dropdown/dropdown-item-that-opens-modal.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/popover/dropdown/dropdown-item.ts
- projects/angular/src/popover/dropdown/dropdown.spec.ts
- projects/angular/src/popover/dropdown/dropdown.ts
- projects/angular/src/popover/dropdown/providers/dropdown-focus-handler.service.ts
Say you have a dropdown item that opens a modal.
This is what happened before this fix:
1. The `clrDropdownItem` is clicked/activated.
2. The modal is opened and focus is moved to the modal title. (This is the custom dropdown item click event handler.)
3. The dropdown menu is closed and focus is moved to the dropdown trigger.
4. The user has to tab or click into the modal to use it.
5. When the modal is closed, focus is not moved back the dropdown trigger.
This is what happens after this fix:
1. The `clrDropdownItem` is clicked/activated.
2. Focus is moved to the dropdown trigger, but the dropdown menu remains open.
3. The modal is opened and focus is moved to the modal title. (This is the custom dropdown item click event handler.)
3. The dropdown menu is closed.
5. The user does NOT have …
> fix(dropdown): manage focus correctly when a modal is opened

- .storybook/stories/dropdown/dropdown-item-that-opens-modal.stories.ts
This story is for testing a specific interaction. The snapshot is not visually different than the default dropdown story.
This fixes a mistake I made in 510d78c2b87a4ffe4eba1b920d689d6860500401.
> chore(dropdown): remove redundant visual regression test

- .github/workflows/release-preview.yml
- .github/workflows/release.yml
I missed this in c3b0ab50d46196b6f2129c17fa37a9f95f549d05.
That commit did not fully revert ddebc67c694681045ef2a55879454d0fed5399a4.
No.
> chore: fetch just head commit in release workflows

- projects/angular/src/data/datagrid/datagrid-column.ts
The `clr-dg-column` inputs for the min/max filter placeholder values didn't work.
This is a backport of #590 to 13.x.
> fix(datagrid): apply min/max filter placeholder values from column (backport to 13.x)

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-column.ts
The string and number filter components provide the default values.
No.
> chore(datagrid): remove redundant default values for filter placeholders

- projects/angular/src/utils/focus-trap/focus-trap.ts
- projects/demo/src/app/cds-theme-select.component.ts
- projects/demo/src/app/overlay-clipping/overlay-clipping.demo.html
- projects/demo/tsconfig.app.json
- tsconfig.json
The `FocusTrap` is used as a base class. It is not injectable.
This change required minor changes to templates in the demo app.
The `strictInputAccessModifiers` option is implied by `strictTemplates`, so I removed that option.
This is a backport of #593 to 13.x.
No.
> chore: enable Angular's strict checks in library and demo app (backport to 13.x)

- .github/workflows/pr-visual-snapshot-update-bot.yml
This fixes a mistake I made in #589.
Without this change, the visual snapshot changes patch may not be able to be cleanly applied.
> chore: checkout the correct commit in "PR Visual Snapshot Update Bot"

- projects/angular/src/forms/combobox/combobox.ts
- projects/angular/src/forms/combobox/providers/combobox-focus-handler.service.ts
Original issue: https://github.com/vmware-clarity/ng-clarity/issues/612
After opening the combobox you have to scroll to find the selected item.
Issue Number: CDE-137
After opening the selected item will be in the view and focused.
> feat(combobox): scroll to selected value on open

- projects/angular/src/utils/focus-trap/focus-trap.directive.spec.ts
A change was made in Angular 15.2.5 to stop automatically unquoting CSS values. That change broke our focus trap tests.
> chore(focus-trap): unquote style values in test component

- projects/angular/src/popover/dropdown/dropdown-item.ts
Either 1481ce1fa6936b116b2ee10bd4b12323fe369ba5 didn't fully work, or something else changed.
This is backport of 2a4ff8b9c8b4ab5b8f87b8bef1c03b1454d24204 (#600) to 13.x.
closes #599
> fix(dropdown): prevent default `click` event if item is disabled (backport to 13.x)

- projects/angular/clarity.api.md
- projects/angular/src/utils/popover/all.spec.ts
- projects/angular/src/utils/popover/index.ts
- projects/angular/src/utils/popover/popover-host.directive.ts
- projects/angular/src/utils/popover/stop-escape-propagation.directive.spec.ts
- projects/angular/src/utils/popover/stop-escape-propagation.directive.ts
This allows the Angular compiler to properly type check templates that have components that use the stop propagation directive.
closes #569
Bugfix
The Angular Language Service crashes or is otherwise unable to type-check components that use the stop propagation directive due to it not being exported.
Issue Number: #569
The stop propagation directive is now exported, so the Angular Language Service should be able to import it for type checking.
No.
> fix(popover): export stop propagation directive

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-row.html
- projects/angular/src/data/datagrid/datagrid-row.spec.ts
- projects/angular/src/data/datagrid/datagrid-row.ts
The row selection mode (`clrDgRowSelection`) feature uses a top-level label to wrap around the entire row in order to proxy clicks to the appropriate checkbox. This feature is deprecated, but cannot be removed for legacy reasons. 
Issue Number: Resolves #378 . CDE-5
The label wrapping the row has been replaced with a div that proxies click events to trigger the appropriate row selection (single vs multi).
> fix(datagrid): change label around clickable row

- .storybook/stories/alert/alert.stories.ts
- .storybook/stories/button/button-group.stories.ts
- .storybook/stories/datagrid/datagrid-column.stories.ts
- .storybook/stories/datagrid/datagrid.stories.ts
- .storybook/stories/modal/modal.stories.ts
- projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
- projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
- projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
- projects/angular/src/layout/vertical-nav/vertical-nav.spec.ts
- projects/angular/src/modal/modal.spec.ts
- projects/angular/src/wizard/wizard-stepnav-item.spec.ts
This is a backport of 6d90a51ca659e59e2ec8cbc6dab45157c4ed9302 (#622) to 13.x.
> chore: use `commonStringsDefault` instead of creating service instance (backport to 13.x)

- projects/angular/src/accordion/stepper/stepper-panel.spec.ts
- projects/angular/src/data/datagrid/datagrid-column-toggle.spec.ts
- projects/angular/src/data/datagrid/datagrid-detail.spec.ts
- projects/angular/src/data/datagrid/datagrid-filter.spec.ts
- projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
- projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
- projects/angular/src/data/datagrid/datagrid.spec.ts
- projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
- projects/angular/src/layout/nav/header.spec.ts
- projects/angular/src/layout/vertical-nav/vertical-nav-group.spec.ts
- projects/angular/src/layout/vertical-nav/vertical-nav.spec.ts
- projects/angular/src/modal/modal.spec.ts
- projects/angular/src/wizard/wizard-stepnav-item.spec.ts
This makes the tests directly assert the actual result.
This is a backport of e0d9810c38e6006b59777a1bb19a8c656cc26af9 (#630) to 13.x.
> chore: assert actual string values instead of common string values (backport to 13.x)

- projects/angular/clarity.api.md
- projects/angular/src/button/button-group/button-group.ts
- projects/angular/src/data/datagrid/datagrid-action-overflow.ts
- projects/angular/src/data/datagrid/datagrid-column-toggle.ts
- projects/angular/src/data/datagrid/datagrid-column.ts
- projects/angular/src/forms/combobox/combobox.ts
- projects/angular/src/forms/datepicker/date-container.ts
- projects/angular/src/layout/tabs/tabs.ts
- projects/angular/src/popover/dropdown/dropdown.ts
- projects/angular/src/popover/signpost/signpost.ts
- projects/angular/src/popover/tooltip/tooltip.ts
- projects/angular/src/utils/popover/index.ts
- projects/angular/src/utils/popover/popover-host.directive.ts
- projects/demo/src/app/popovers/dummy-anchor.ts
This allows the Angular compiler to properly type check templates that have components that use the popover host directive.
part of #666
> fix(popover): export popover host directive

- projects/angular/clarity.api.md
- projects/angular/src/layout/nav/nav-level.ts
- projects/angular/src/utils/focus/focus-trap/index.ts
- projects/angular/src/utils/focus/focus-trap/standalone-cdk-trap-focus.directive.ts
- projects/angular/src/utils/index.ts
This allows the Angular compiler to properly type check templates that have components that use the standalone `CdkTrapFocus` directive.
part of #666
> fix(nav): export standalone `CdkTrapFocus` directive

- projects/angular/src/data/stack-view/_stack-view.clarity.scss
Currently, there is static height 55vh set to the stack-view when in modal.
Issue Number: CDE-10
Now there is no static height set to the stack-view when in modal.
If some application relies on the 55vh height set to the stack-view in modal, it can be set directly on the modal.
> fix(stack-view): remove static height in modals

- .storybook/stories/wizard/wizard.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
- projects/angular/src/wizard/test-components/api-wizard.mock.ts
- projects/angular/src/wizard/wizard.html
- projects/angular/src/wizard/wizard.spec.ts
- projects/angular/src/wizard/wizard.ts
Currently the stepnav wrapper is using <nav> element and there is no aria-label or possibility to set one for it.
Issue Number: CDE-153
The stepnav wrapper is now using a <div> element with role="region" and an aria-label. Which can also be set trough the clrWizardStepnavAriaLabel input.
> feat(wizard): add custom aria-label for stepnav section

- projects/angular/clarity.api.md
- projects/angular/src/wizard/wizard-custom-tags.ts
This is a backport of 56e8868e3425a6389c5c4453007ef33d72ed80b5 (#661) to 13.x.
> chore(wizard): remove unused `clr-wizard-pagetitle` selector (backport #661 to 13.x)

- projects/angular/clarity.api.md
- projects/angular/src/wizard/wizard.html
- projects/angular/src/wizard/wizard.ts
This is the wizard page title, not the main wizard title.
This is a backport of 394e2b47d3a4aeb56c01bc7784ddefd680cab4c8 (#660) to 13.x.
> chore(wizard): rename `wizardTitle` property/template to `pageTitle` (backport of #660 to 13.x)

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-row.ts
- projects/angular/src/data/datagrid/datagrid.spec.ts
- projects/angular/src/data/datagrid/datagrid.ts
Previous behavior:
If the row item references are changed but the row component instances are not changed, the selection was not re-mapped to the new item instances.
This was because the selection was only re-mapped if the rows `QueryList` emitted a change. If `[ngForTrackBy]` is used and the items collection is updated to new instances of the same items, the selection was not mapped to the new item instances. This caused the datagrid to display an inconsistent/incorrect view (e.g. a non-zero selection count but no rows actually checked).
New behavior:
If the row item references are changed, the selection is re-mapped to the new object references even if the rows `QueryList` does not emit a change.
closes #671
This is a backport of 701bc436c48a9c0c3f8305076a339642be91f42f (#672) to 13.x.
> fix(datagrid): re-map selection if row item references are changed (backport of #672 to 13.x)

- .eslintrc.js
- projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter-impl.spec.ts
- projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter-impl.spec.ts
- projects/angular/src/data/datagrid/datagrid-action-overflow.spec.ts
- projects/angular/src/data/datagrid/datagrid-column.spec.ts
- projects/angular/src/data/datagrid/datagrid-filter.spec.ts
- projects/angular/src/data/datagrid/datagrid.spec.ts
- projects/angular/src/data/datagrid/render/noop-dom-adapter.ts
- projects/angular/src/forms/common/if-control-state/abstract-if-state.ts
- projects/angular/src/forms/datepicker/date-input.spec.ts
- projects/angular/src/popover/dropdown/providers/dropdown-focus-handler.spec.ts
- projects/angular/src/utils/dom-adapter/dom-adapter.mock.ts
- projects/angular/src/wizard/providers/page-collection.service.mock.ts
This is a backport of 5f8b534769e55958575fad8bdd9ebd5103c43f41 (#676) to 13.x.
> chore: clean up eslint ignore comments (backport of #676 to 13.x)

- projects/angular/src/button/button-group/button.ts
- projects/angular/src/button/button-loading/loading-button.ts
- projects/angular/src/data/datagrid/render/header-renderer.ts
- projects/angular/src/data/stack-view/stack-block.ts
- projects/angular/src/emphasis/alert/alert.ts
- projects/angular/src/forms/combobox/combobox.ts
- projects/angular/src/forms/datepicker/date-input.ts
- projects/angular/src/forms/datepicker/providers/datepicker-focus.service.spec.ts
- projects/angular/src/layout/vertical-nav/vertical-nav-group.ts
- projects/angular/src/layout/vertical-nav/vertical-nav.ts
- projects/angular/src/modal/modal.ts
- projects/angular/src/utils/conditional/if-active.directive.ts
- projects/angular/src/utils/conditional/if-expanded.directive.ts
- projects/angular/src/utils/conditional/if-open.directive.ts
- projects/angular/src/utils/focus/key-focus/key-focus.ts
- projects/angular/src/utils/popover/popover-close-button.ts
- projects/angular/src/utils/popover/popover-content.ts
- projects/angular/src/utils/popover/popover-open-close-button.ts
- projects/angular/src/wizard/wizard-button.ts
- projects/angular/src/wizard/wizard-header-action.ts
- projects/angular/src/wizard/wizard-page.ts
- projects/angular/src/wizard/wizard.ts
This is a backport of 05deac5a9b36634fa0f927e9917f3d9c291d1760 (#675) to 13.x.
> chore: simplify `EventEmitter` property declarations (backport of #675 to 13.x)

- .storybook/manager-head.html
Update storybook google analytics to use GA4 and gtag. GA3 (current implementation) will be disabled on July 1.
> chore(analytics): update storybook config to use gtag/ga4

- projects/angular/src/utils/popover/popover-content.ts
The combobox popover is flashing on option selection due to opacity change of the popover content.  Opacity was set to 0 when the "realign" is called which was not needed in this case. It is needed only on initial creation of the popover when the position of it is top: 0, left:0 and then when it's in the right position it would appear.
Issue Number: CDE-11
No longer flashing.
> fix(combobox): prevent flashing on option selected

- projects/angular/src/forms/styles/_select.clarity.scss
The difference on hover is that it's slightly darker:
Left: default Right: hover
Currently it was set to change 'color' on hover but we use background image for the caret and it was not working.
Using proper image with the right color on hover.
> fix(select): change caret color on hover

- .storybook/stories/header/header.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/layout/nav/header.spec.ts
- projects/angular/src/layout/nav/header.ts
The `clr-header` element will now have `role="banner"` by default. This can be overridden in applications by setting the attribute to a different value, e.g. `role="generic"`. Alternatively, the `role` attribute can be removed entirely by binding `[role]="undefined"`.
CDE-452
> fix(header): add `role="banner"` by default

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
Currently the css was changing the `color` of the button in manage columns popover which does not affect the icon color.
Hovering is now changing the close button icon color in manage columns popover.
> fix(datagrid): change manage columns popover close button color on hover

- projects/angular/src/modal/modal.ts
This commit makes `13.x` more consistent with `main`.
I missed this change in 6dce60179546dde6e64a23e168e876ff11e9d85d.
> chore(modal): declare `_open` property on a single line

- projects/angular/src/utils/popover/stop-escape-propagation.directive.spec.ts
This is the warning that was being logged:
```
Element matching '[cdkFocusInitial]' is not focusable.
```
I think the `.modal-title-wrapper` element was failing the visibility check while the modal was being closed. Detecting changes after the component is stable fixes it.
> chore: prevent "element not focusable" warning in tests

- projects/angular/src/popover/tooltip/_tooltips.clarity.scss
The previous change to introduce a fix for VPAT-617 meant the user was unable to copy text out of a tooltip because the ::after content overlays the tooltip content.
This change adds a -1 z-index to the ::after so that it is underneath which exposes the tooltip content div to allow text to be selected and copied.
User hovers over tooltip trigger, tooltip displays, user then mouses over the tooltip content, but cannot select any text due to the overlaid ::after content.
User can now select text from tooltip and copy it to their clipboard.
before:
after:
> fix(tooltip): allow user to interact with tooltip content using mouse

- .github/workflows/pr-comment-bot.yml
- .github/workflows/pr-preview.yml
This change is helpful in cases where only the visual regression tests fail. It may be helpful to have a preview of the PR to inspect.
> chore: deploy pr preview whether or not build succeeds if docs generated

- projects/angular/clarity.api.md
- projects/angular/src/data/stack-view/stack-block.ts
The stack block handles the space and enter keys to toggle expansion. We don't want the stack block to expand or collapse on click, space, or enter inside of an input.
The stack block prevents default on `keydown.space` which prevents the space from being "typed" into the input. This change fixes that as well.
closes #710
> fix(stack-view): ignore input events in stack block

- projects/angular/src/layout/nav/_links.clarity.scss
The styles of the links override the button ones and this creates visual issues due to the selectors of `:link` being with higher specificity than the `.btn` one. 
Not setting the new styles on elements with `.btn` and `.nav-links` because they don't need it.
> fix(links): exclude btn and nav-link from styling

- playwright.config.ts
- tests/visual-snapshots.spec.ts
Reduces VRT duration from ~11m to ~6-7m. Further improvements can be made using a matrix and sharding across different jobs but the current structure of handling the unused screenshots would cause problems. We can investigate those later.
> chore(vrt): expand parallel workers for tests

- projects/angular/src/forms/combobox/combobox.ts
The `invalid` class on the combobox wrapper is set even if the control is not touched.
Issue Number: CDE-1122
The class is now being set if the control is touched and invalid.
> fix(combobox): add touched condition to invalid validation

- projects/angular/clarity.api.md
- projects/angular/src/data/stack-view/stack-block.ts
This is a backport of b3fc2c6cb82ed7bdb53f474cbcc8553c0894358b (#841) to 13.x.
The stack block handles the space and enter keys to toggle expansion. We don't want the stack block to expand or collapse on click, space, or enter inside of an input.
The stack block prevents default on `keydown.space` which prevents the space from being "typed" into the input. This change fixes that as well.
closes #710
> fix(stack-view): ignore input events in stack block (backport to 13.x)

- projects/angular/clarity.api.md
- projects/angular/src/popover/signpost/signpost-trigger.spec.ts
- projects/angular/src/popover/signpost/signpost-trigger.ts
- projects/angular/src/popover/signpost/signpost.spec.ts
- projects/angular/src/popover/signpost/signpost.ts
This is a backport of dd1504aac25af2e959f15583a144c28c2b8c6f59 (#1052) to 16.x.
This prevents overriding the visible text of a custom signpost trigger.
VPAT-774
> fix(signpost): provide default `aria-label` only on default trigger

- .github/workflows/pr-build.yml
This is a backport of 1f35ac2da70481bc006e23eb0a7d5f8924d5a1cc (#1045) to 15.x.
The previous command updated all unlisted Angular packages to v17.
> chore: prevent installing Angular 17 instead of Angular 16

- .storybook/stories/modal/modal.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/modal/modal.ts
- projects/angular/src/wizard/_wizard.clarity.scss
- projects/angular/src/wizard/wizard.html
- projects/angular/src/wizard/wizard.ts
- projects/demo/src/app/wizard/wizard-inline.demo.html
- projects/demo/src/app/wizard/wizard-inline.demo.ts
- projects/demo/src/app/wizard/wizard.demo.module.ts
- projects/demo/src/app/wizard/wizard.demo.routing.ts
- projects/demo/src/app/wizard/wizard.demo.ts
This reverts commit 7470769480b843dc332adbd25f67624ce4979e56 (#419), removes the deprecated comments, and adds a comment explaining when inline wizards are used.
Inline wizards are used by vSphere plugins to display a wizard inside an iframe that is inside a modal.
CDE-154
> feat(wizard): add back inline wizards in 15.x

- .storybook/stories/modal/modal.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/modal/modal.ts
- projects/angular/src/wizard/_wizard.clarity.scss
- projects/angular/src/wizard/wizard.html
- projects/angular/src/wizard/wizard.ts
- projects/demo/src/app/wizard/wizard-inline.demo.html
- projects/demo/src/app/wizard/wizard-inline.demo.ts
- projects/demo/src/app/wizard/wizard.demo.module.ts
- projects/demo/src/app/wizard/wizard.demo.routing.ts
- projects/demo/src/app/wizard/wizard.demo.ts
This is a port of c5d3f09d50af56c27f50476c88c0a0816b96d1e6 (#1067) to 16.x.
This reverts commit 7470769480b843dc332adbd25f67624ce4979e56 (#419), removes the deprecated comments, and adds a comment explaining when inline wizards are used.
Inline wizards are used by vSphere plugins to display a wizard inside an iframe that is inside a modal.
CDE-154
> feat(wizard): add back inline wizards in 16.x

- .storybook/stories/progress-bar/progress-bar.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/progress/progress-bars/_variables.progress-bars.scss
- projects/angular/src/progress/progress-bars/progress-bar.spec.ts
- projects/angular/src/progress/progress-bars/progress-bar.ts
- projects/demo/src/app/progress-bars/progress-bar-component.html
Current API uses different properties for assign colors to progress bar `clrSuccess`, `clrWarning` and `clrDanger`.
Issue Number: CDE-1406
The new API is using property `clrColor` with possible values `'success' | 'warning' | 'danger'` for better understanding and ease of use.
BREAKING CHANGES: API properties used for color assign `clrSuccess`, `clrWarning` and `clrDanger` are replaced with single property `clrColor` with possible values `'success' | 'warning' | 'danger'`.
> feat(progress-bar): change color api

- projects/angular/src/accordion/accordion.ts
An instance of the accordion component should only care about its own panels. Including nested accordions' panels causes an error when trying to update panels that don't belong the parent instance.
closes #1118
Bugfix
Issue Number: #1118
No JS error with nested accordion panels.
No.
> fix(accordion): prevent error with nested accordions

- .github/workflows/pr-visual-snapshot-update-bot.yml
There was code to cleanup visual snapshot update branches if no changes, but that job only runs after after failed build. This resulted in visual snapshot update branches persisting after successful builds.
We can solve this by immediately deleting the visual snapshot branches. We just need the visual snapshot update commit in the repo. There is no need to keep the branches around for any length of time.
> chore: delete visual snapshot update branch immediately

- projects/angular/src/button/button-loading/loading-button.ts
This is a port of 669297716df9695cccaec6cf7599ed1ba394dba4 (#1141) to 17.x.
The button text/content should only be faded when transitioning to or from a non-default state.
CDE-1596
closes #1075
Bugfix
Buttons using a `[clrLoading]` directive have the button text faded in on page load. Buttons without the directive do not.
Issue Number: #1075, CDE-1596
The button text/content should only be faded when transitioning to or from a non-default state.
No.
> fix(button): skip animation on first render of loading button (port to 17.x)

- projects/angular/src/emphasis/alert/alert.ts
- projects/angular/src/emphasis/alert/alerts.spec.ts
This change prevents if the multi-alerts `clr-alerts` component contains an alert with `[clrAlertClosed]` set to false. The error was thrown because the code attempted to close an alert that was never rendered.
CDE-1606
closes #92
Bugfix
JS error thrown if an alert in a multi-alert is initially closed. The error was thrown because the code attempted to close an alert that was never rendered.
Issue Number: #92
No JS error thrown if an alert in a multi-alert is initially closed. The `MultiAlertService#close` method is not called if the alerts have not yet been rendered.
No.
> fix(alert): prevent error if alert is initially closed

- projects/angular/src/emphasis/alert/alert.ts
- projects/angular/src/emphasis/alert/alerts.spec.ts
This is port of b7841d74a18c5b6fa4e7dde62ce92f7733fa6718 (#1156) to 15.x.
This change prevents if the multi-alerts `clr-alerts` component contains an alert with `[clrAlertClosed]` set to false. The error was thrown because the code attempted to close an alert that was never rendered.
CDE-1606
closes #92
Bugfix
JS error thrown if an alert in a multi-alert is initially closed. The error was thrown because the code attempted to close an alert that was never rendered.
Issue Number: #92
No JS error thrown if an alert in a multi-alert is initially closed. The `MultiAlertService#close` method is not called if the alerts have not yet been rendered.
No.
> fix(alert): prevent error if alert is initially closed (port to 15.x)

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
This is a port of 5599159a4cb89a19b2d430f72e1beeec98b4e946 (#774) to 17.x.
- remove rule for missing `datagrid-popover` layer
- remove redundant `datagrid-row-sticky` z-index declaration
- use correct z-index for sticky row elements
- use correct z-index for header row sticky element
closes #773
> fix(datagrid): use correct layers, remove no-op z-indexes (port to 17.x)

- projects/angular/src/layout/_card.clarity.scss
- projects/angular/src/layout/_properties.card.scss
Port of #1166 
When hovering over clickable card the border width animates from 1px to 2px, causing the text content contained within the card to noticeably shift. This can be seen when hovering the clickable card on our [website](https://clarity.design/documentation/card/code#clickable-cards) and our
[storybook](https://storybook.clarity.design/?path=/story/card-card--default).
Issue Number: CDE-917
This changes the clickable border-width token to 1px (which is the correct value for non-hovered clickable cards), and then uses the box-shadow to set a 1px shadow around the element. Since both the box-shadow and the border-color are the same color, and they're both 1px by default, the …
> fix(card): resolve clickable card hover shifting text (#1166)

- package-lock.json
- package.json
- projects/angular/src/data/datagrid/datagrid-if-expanded.service.ts
- projects/angular/src/utils/chocolate/willy-wonka.ts
- projects/angular/src/utils/focus/key-focus/key-focus.ts
- projects/angular/src/wizard/providers/button-hub.service.ts
- projects/angular/src/wizard/providers/wizard-navigation.service.ts
- projects/angular/src/wizard/wizard.spec.ts
- projects/angular/src/wizard/wizard.ts
- projects/demo/src/app/forms/dynamic-controls/dynamic-controls.demo.ts
This prevents the following build error on Angular 17:
```
./node_modules/@angular/core/fesm2022/testing.mjs:283:11-25
- Error: export 'firstValueFrom' (imported as 'firstValueFrom') was not found in 'rxjs'
```
This issue was introduced in 17.1.0. See angular/angular#54210 for more details.
Note: I changed `EventEmitter#next` to `EventEmitter#emit` only where required to get a successful build.
> chore: update `rxjs` package

- projects/angular/src/button/button-loading/loading-button.ts
In #1141 the loading button contents were added into a div to prevent the button from animating on the initial render. 
Issue Number: CDE-1628
The div is changed to a span because adding a div inside of a button is technically not semantically correct html.
> fix(button): change loading button conents from div to span

- projects/angular/src/utils/popover/providers/popover-position.service.spec.ts
- projects/angular/src/utils/popover/providers/popover-position.service.ts
> fix(popover): update positioning logic to render within body

- projects/angular/src/popover/signpost/signpost-content.ts
When you open a signpost with a scroll you can't use keyboard due to missing focus on the content.
Issue Number: CDE-1397
Now you can focus the content and scroll freely with the keyboard.
> fix(signpost): allow keyboard scrolling in overflow content (backport to 15.x)

- projects/angular/clarity.api.md
- projects/angular/src/forms/password/password-container.spec.ts
- projects/angular/src/forms/password/password-container.ts
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
Clarity uses constants/static text to label the show/ hide icon corresponding to the password input field, this is not unique for each clr-password-container input. It currently only ever reads as Show password / Hide password when using a screen reader.
Issue Number: CDE-1179
Each individual show/hide icon button corresponding to a password field will now announce the unique label name (associated to that field)  in addition to Show password / Hide password when using a screen reader.
> fix(a11y): clr-password-container show/hide Icon does not have unique label

- package-lock.json
- package.json
- projects/angular/package.json
- projects/ui/package.json
BREAKING CHANGE: Bump the cds/core peer dependency to the latest, 6.9.2
> feat(deps): bump cds/core to 6.9.2

- projects/angular/src/accordion/stepper/models/stepper.model.ts
- projects/angular/src/accordion/stepper/providers/stepper.service.ts
- projects/angular/src/accordion/stepper/stepper-panel.ts
- projects/angular/src/accordion/stepper/stepper.spec.ts
This is a port of dcb5c293d2b27ba8293e0796f6d6350b4641b47c (#1184) to 16.x.
- Set the panel status to invalid immediately when the form becomes invalid.
- Set the panel status back to valid immediately when the form becomes valid after being invalid.
CDE-1463
> fix(stepper): improve panel status updates (port to 16.x)

- projects/angular/src/accordion/stepper/models/stepper.model.ts
- projects/angular/src/accordion/stepper/providers/stepper.service.ts
- projects/angular/src/accordion/stepper/stepper-panel.ts
- projects/angular/src/accordion/stepper/stepper.spec.ts
This is a port of dcb5c293d2b27ba8293e0796f6d6350b4641b47c (#1184) to 15.x.
- Set the panel status to invalid immediately when the form becomes invalid.
- Set the panel status back to valid immediately when the form becomes valid after being invalid.
CDE-1463
> fix(stepper): improve panel status updates (port to 15.x)

- angular.json
- docs/INSTALLATION.md
- projects/angular/README.md
- projects/ui/README.md
- projects/ui/src/clr-ui.scss
Currently we import both light and dark core tokens inside `clr-ui` and they are all exported with it but that creates  disability to use different `@cds/core` version from what we specify as peer dependency for `clr-ui`.
Issue Number: CDE-1639
Clr-ui no longer includes core tokens and these should be imported individually per project. Steps are described in clr-ui readme.
BREAKING CHANGE: clr-ui no longer includes core tokens and they need to be included individually per project when importing clr-ui ( step 2 in clr-ui readme ).
> fix(ui): remove core imports in clr-ui and add documentation steps

- projects/ui/src/shim.cds-core.scss
When adding the v16 shim overrides for font-weight, the body font-weight was accidentally included in the list. 
The body font-weight value is removed, resulting in the body font returning to the correct 400 weight.
> fix(shim): remove body-font-weight override

- .github/workflows/pr-visual-snapshot-update-bot.yml
This is port of f51ce5cd366a111098b5c9951efd3a3822979300 (#1135) to the new `main` branch after the v17 release.
This makes it easier to find the status (and log) of the update bot workflow run for a pull request.
The job name was removed to prevent an error in the status action.
> chore: report visual snapshot update bot status to pull request

- projects/ui/src/shim.cds-core.scss
Tree node have strictly defined height of 32px.
Issue Number: CDE-1683
Tree node have defined min-height of 32px.
> fix(tree-view): set node `min-height` instead of `height` (backport of #1264)

- projects/ui/src/shim.cds-core.scss
Backport of https://github.com/vmware-clarity/ng-clarity/commit/f8cd042f72946a216e14bc74e2ccf638f2c9d29d
When the action overflow button is in a pressed state, the icon color shifts to a lighter tone background color and the icon appears to disappear due to a lack of color contrast with the hover background color. this is a result of the icon color being mapped to a background color in the system, when it should be mapped to color-active.
Issue Number: CDE-1689
The icon does not appear to disappear when the user is pressing the button.
> fix(datagrid): fix pressed action overflow icon color (backport to 16.x)

- .storybook/stories/datagrid/datagrid-expandable-row.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/utils/animations/expandable-animation/expandable-animation.ts
In expandable row in datagrid overflow is set to hidden in occupancies.
Issue Number: CDE-1692
In expandable row in datagrid overflow is set to hidden only during animation.
> fix(datagrid): set expandable rows overflow hidden only during animation

- projects/angular/clarity.api.md
- projects/angular/src/layout/tabs/tab-content.ts
- projects/angular/src/layout/tabs/tab-link.directive.ts
Issue Number: CDE-1354
This PR fixes getter method ariaLabelledBy to return correct tabLinkId. Previously nothing was found in the getter function so the aria-labelledby attrbute was not set. To be able to find the correct tabLink I had to expose a getter of the id of the tabLink.
> fix(tabs): fix aria-labelledby attribute

- projects/angular/clarity.api.md
- projects/angular/src/layout/tabs/tab-content.ts
- projects/angular/src/layout/tabs/tab-link.directive.ts
Issue Number: CDE-1354
This PR fixes getter method ariaLabelledBy to return correct tabLinkId. Previously nothing was found in the getter function so the aria-labelledby attrbute was not set. To be able to find the correct tabLink I had to expose a getter of the id of the tabLink.
Port of https://github.com/vmware-clarity/ng-clarity/pull/1309 to 16.x
> fix(tabs): fix aria-labelledby attribute (#1309)

- projects/angular/src/forms/datepicker/daypicker.ts
- projects/angular/src/forms/datepicker/monthpicker.ts
- projects/angular/src/forms/datepicker/yearpicker.ts
A11y Clarity Datepicker - Screen reader is reading extra information upon opening
Extra date information is announced after the date is announced the first time by the screen reader i.e the date is announced twice when the Datepicker dialog is opened. 
Issue Number: [CDE-790](https://jira.eng.vmware.com/browse/CDE-790) & [VPAT-21915](https://jira.eng.vmware.com/browse/VPAT-21915)
The date is announced only once by the screen reader when the Datepicker is opened.
This is observed in NVDA on windows in Chrome/ IE & Firefox.
> fix(a11y): datepicker - screen reader is reading extra information on opening

- projects/angular/clarity.api.md
- projects/angular/src/accordion/accordion-panel.html
- projects/angular/src/accordion/accordion-panel.ts
- projects/angular/src/accordion/stepper/stepper-panel.spec.ts
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
In the Stepper, when the step is complete, keyboard focus moves to the next step but there's no indication that the previous step is completed by the screen reader.
Issue Number: [CDE-699](https://jira.eng.vmware.com/browse/CDE-699)
The screen reader will announce that the current step is complete (or failed) and move focus to the next step or stay in the same step in case of an error.
> fix(a11y): stepper-completed step does not have accessible notification after completion

- projects/angular/clarity.api.md
- projects/angular/src/accordion/accordion-panel.html
- projects/angular/src/accordion/accordion-panel.ts
- projects/angular/src/accordion/stepper/stepper-panel.spec.ts
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
In the Stepper, when the step is complete, keyboard focus moves to the next step but there's no indication that the previous step is completed by the screen reader.
Issue Number: [CDE-699](https://jira.eng.vmware.com/browse/CDE-699)
The screen reader will announce that the current step is complete (or failed) and move focus to the next step or stay in the same step in case of an error.
---------
Co-authored-by: Andrea Fernandes <andreaf1@vmware.com>
> fix(a11y): stepper-completed step does not have accessible notification after completion (#1334)

- projects/angular/clarity.api.md
- projects/angular/src/forms/radio/radio-container.ts
Issue Number: [CDE-1196](https://jira.eng.vmware.com/browse/CDE-1196)
This was previously fixed using `aria-label`, after discussion with the accessibility team, it was recommended to use `aria-labelledby="[id-of-form-group-name]"` instead of `aria-label="[Name of Group]"`. Also,`aria-labelledby` is better from the localization perspective.
> fix(a11y): radio group label is not announced by screen readers

- projects/angular/src/data/datagrid/datagrid-row.html
- projects/angular/src/data/datagrid/datagrid.html
- projects/angular/src/data/datagrid/datagrid.spec.ts
Issue Number: [CDE-252](https://jira.eng.vmware.com/browse/CDE-252)
Removed the aria-label and added clr-sr-only text, which is now announced by the screenreader in NVDA browse mode.
Also fixed issue related to [CDE-1411](https://jira.eng.vmware.com/browse/CDE-1411), for v17. It was fixed only for v15 & v16 previously.
> fix(a11y): aria-label in datagrid header is not announced by screen reader

- projects/angular/src/accordion/accordion-panel.html
- projects/angular/src/accordion/stepper/stepper-panel.spec.ts
- projects/angular/src/accordion/stepper/stepper-panel.ts
Voice Over on Safari was reading the next step header before announcing the status of the previous step, which is either complete or an error. 
Issue Number: [CDE-699](https://jira.eng.vmware.com/browse/CDE-699)
Added a delay for the stepper header button focus so that the status of the previous step is announced before the next step is read.
> fix(a11y): stepper-announce step complete/error on vo safari

- projects/angular/src/forms/STYLES.md
- projects/angular/src/layout/STYLES.md
- projects/angular/src/layout/tabs/STYLES.md
- Fix bad table syntax in login style documentation. This will fix a display bug on the website.
- Rename forms style documentation file for case sensitivity. This will make the file included in the build.
- Use "CSS Classes" instead "Class names" headings. This will make the website include the warning about overriding CSS classes.
> chore: various fixes for style documentation

- projects/angular/src/modal/modal.html
- projects/angular/src/modal/modal.spec.ts
- projects/angular/src/modal/modal.ts
Bugfix
If you set `[clrModalLabelledById]` to an empty string, the `aria-labelledby` attribute of the modal dialog element is set to an empty value.
This behavior can be seen in the modal stories since the input is defaulted to an empty string. We can't default it to the modal id because that is not known until the component is instantiated.
Issue Number: CDE-2050
If you set `[clrModalLabelledById]` to an empty string, the `aria-labelledby` attribute of the modal dialog element is set to the modal id.
No.
> fix(modal): fall back to modal id for dialog `aria-labelledby` attribute

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-detail-header.ts
- projects/angular/src/data/datagrid/providers/detail.service.ts
In browser zoom more than 250%, when we open the details pane and close it , the keyboard focus is not returned back to the button that was used to open it. This is due to the fact that when the page is zoomed in, the button is not visible on the page, and is available only once the detail pane is closed.
Issue Number: [CDE-1205](https://jira.eng.vmware.com/browse/CDE-1205)
Wait for the detail pane to close and then manually focus on the button used to open it.
> fix(a11y): return focus to datagrid detail pane toggle button after pane closed in zoom more than 250%

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-detail-header.ts
- projects/angular/src/data/datagrid/providers/detail.service.ts
Issue Number: [CDE-2051](https://jira.eng.vmware.com/browse/CDE-2051)
Focus is returned to the button that opened the pane on ESC key in zoom more than 250%.
> fix(a11y): return focus to datagrid detail pane toggle button after esc with zoom 250%

- projects/angular/src/timeline/timeline-step.ts
- projects/angular/src/timeline/timeline.ts
Due to the absence of semantic tags `<ul>` and `<li>` in the angular version of the timeline component, screen readers do not announce the number of steps in the timeline.
Issue Number: [CDE-1181](https://jira.eng.vmware.com/browse/CDE-1181)
Added aria roles: `role="list"` to the timeline container and `role="listitem"` to each timeline step so that screen readers consider the timeline as a list and announce the number of steps.
> fix(a11y): timeline steps should have a list structure

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-action-overflow.ts
- projects/angular/src/data/datagrid/datagrid-row.html
- projects/angular/src/data/datagrid/datagrid.html
- projects/angular/src/data/datagrid/datagrid.ts
All datagrid static inputs and buttons are focusable by `tab` key. 
Issue Number: CDE-1943
Static datagrid inputs and buttons are focusable only within the datagrid by `Arrow keys` and `PageUp/Down` keys.
> fix(datagrid): remove cell input focus by `tab` key

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
- projects/angular/src/data/datagrid/datagrid.html
Currently loading rows are using `clr-dg-row` which shows the sticky columns if available
Issue Number: CDE-2069
Hide sticky columns for loading row.
> fix(datagrid): hide sticky columns for loading more items row

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
- projects/angular/src/data/datagrid/providers/detail.service.ts
When closing detail in datagrid trough the 'X' button it loses the focus for a second which triggers a scroll inside and fails to focus the button triger sometimes.
Issue Number: CDE-2043
Overlay detail is no longer setting the datagrid to `display:none` which block us from return the focus to the trigger at the right moment and we moved the focus trigger just before the close so we skip the moment where the focus is lost and it focuses the body.
> fix(datagrid): retain focus on closing detail

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-detail-header.ts
- projects/angular/src/data/datagrid/datagrid-detail.ts
- projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.ts
- projects/angular/src/data/datagrid/datagrid.ts
- projects/angular/src/data/datagrid/providers/detail.service.ts
- projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
- projects/demo/src/app/datagrid/virtual-scroll-client-side/virtual-scroll-client-side.html
- projects/demo/src/app/datagrid/virtual-scroll-client-side/virtual-scroll-client-side.ts
Backport f402878c67cc610d7f4f6360f0dd3ee2dc849454 from #1431.
Backport 984ecd1da01c8a84d1673c51b3481ec1f6d551b6 from #1437
Virtual scroller load extra page when close detail page.
Issue Number: CDE-2070
Virtual scroller don't load extra page when close detail page.
> fix(datagrid): virtual scroll load extra page for details (backport to 16.x)

- projects/angular/src/forms/combobox/combobox.spec.ts
- projects/angular/src/forms/datepicker/date-container.spec.ts
- projects/angular/src/forms/datepicker/date-input.spec.ts
- projects/angular/src/forms/tests/container.spec.ts
- projects/angular/src/layout/vertical-nav/vertical-nav-group.spec.ts
- projects/demo/src/app/datagrid/full/full.ts
- projects/demo/src/app/datagrid/preserve-selection/preserve-selection.ts
- projects/demo/src/app/datagrid/selection-single/selection-single.ts
- projects/demo/src/app/datagrid/selection/selection.ts
- projects/demo/src/app/datagrid/server-driven/server-driven.ts
- projects/demo/src/app/datagrid/virtual-scroll-server-side/virtual-scroll-server-side.ts
Legacy `.then` syntax is used in several places.
Issue Number: CDE-2082
Modern `async`/`await` syntax is used.
No.
> chore: use `async`/`await` instead of `.then`

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-filter.spec.ts
- projects/angular/src/data/datagrid/datagrid-filter.ts
- projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
When items get filtered the input loses focus
Issue Number: #1438 
Focus stay on the input
> fix(datagrid): keep filter focus on row changes

- projects/angular/src/popover/dropdown/_dropdown.clarity.scss
Focus outline is hard to be seen in tab overflow due to being cut
Outline have offset and it's clearly visible
> fix(dropdown): add negative offset to item focus outline

- .storybook/stories/datagrid/datagrid-detail.stories.ts
- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-detail.spec.ts
- projects/angular/src/data/datagrid/datagrid-detail.ts
`aria-describedby` is used on the datagrid detail pane instead of `aria-labelledby` 
Issue Number: [CDE-645](https://jira.eng.vmware.com/browse/CDE-645)
- By default if the user does not add anything: `aria-labelledby` will be added by the library with the id of the modal title.
- The user can set additional `aria-labelledby` (using the [clrDetailAriaLabelledBy] input) which could have a value referencing other text on the page , it can have multiple space separated id's. In this case the default title id will be added along with the user defined IDs.
- The user can add `aria-label` (using [clrDetailAriaLabel] input), in this case the aria-label provided will be used. 
- If both …
> fix(a11y): datagrid detail pane has role dialog with no aria label

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
Focus outline for datagrid cells is not visible in firefox browser.
Issue Number: CDE-2124
Using object interaction outline token to show the focus for all browsers.
> fix(datagrid): use outline token for cell focus

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
Backport of #1467 
Focus outline for datagrid cells is not visible in firefox browser.
Issue Number: CDE-2124
Using object interaction outline token to show the focus for all browsers.
> fix(datagrid): use outline token for cell focus (backport to 16.x)

- .storybook/stories/datepicker/datepicker.stories.ts
- .storybook/stories/datepicker/daterangepicker.stories.ts
This prevents the visual regression tests from failing due to the current date being different.
I also changed the default value in the single date picker story to be more readable.
> chore(datepicker): use static dates in date range picker screenshots

- projects/angular/src/button/providers/button-group-focus-handler.spec.ts
- projects/angular/src/data/datagrid/datagrid-action-overflow.spec.ts
- projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.spec.ts
- projects/angular/src/data/datagrid/datagrid.spec.ts
- projects/angular/src/data/datagrid/providers/detail.service.spec.ts
- projects/angular/src/forms/datepicker/date-container.spec.ts
- projects/angular/src/modal/modal.spec.ts
- projects/angular/src/modal/side-panel.spec.ts
- projects/angular/src/wizard/wizard.spec.ts
- Use `toBe` instead of `toEqual`.
- Write assertions as `expect(actualValue).toBe(expectedValue)`.
> chore: refactor active element assertions

- projects/demo/src/app/tooltips/tooltips-angular.html
- projects/ui/src/shim.cds-core.scss
Backport of 3ccaf2818d1043973b9c4b1ccce979f69d86f51b from (#1522) to 16.x.
`list` HTML element have wrong text color in `tooltip` component.
Issue Number: CDE-1700
`list` HTML element have correct text color in `tooltip` component.
> fix(tooltip): text color of nested list (backport to 16.x)

- projects/angular/clarity.api.md
- projects/angular/src/modal/index.ts
- projects/angular/src/modal/modal-configuration.service.ts
- projects/angular/src/modal/modal.module.ts
This fixes a dependency injection error when using the `VmwNgxModalService`.
Bugfix
The following error occurs when using `VmwNgxModalService`:
```
ERROR NullInjectorError: R3InjectorError(Environment Injector)[ClrModalConfigurationService -> ClrModalConfigurationService]: 
NullInjectorError: No provider for ClrModalConfigurationService!
at NullInjector.get (core.mjs:1635:21)
at R3Injector.get (core.mjs:3017:27)
at R3Injector.get (core.mjs:3017:27)
at ChainedInjector.get (core.mjs:5288:32)
at lookupTokenUsingModuleInjector (core.mjs:5631:31)
at getOrCreateInjectable (core.mjs:5677:10)
at …
```
> fix(modal): provide modal config service in root and export

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
- projects/angular/src/data/datagrid/datagrid.html
When using virtual scroller empty space is available after the last row.
Issue Number: CDE-2313
When using virtual scroller there is no empty space after the last row.
> fix(datagrid): virtual scroll empty space after last row

- projects/angular/clarity.api.md
- projects/angular/src/utils/i18n/common-strings.default.ts
- projects/angular/src/utils/i18n/common-strings.interface.ts
- projects/angular/src/wizard/wizard-stepnav-item.spec.ts
- projects/angular/src/wizard/wizard-stepnav-item.ts
- Add "Step" before step number.
- Replace untranslated step status icon labels with translated text.
Bugfix
- For uncompleted steps, the wizard step nav reads "1 [step title]". I doesn't read "step" before the step number.
- For completed steps, the wizard step nav reads "complete 1 [step title] completed". The first "complete" is not translated, and the second one is redundant.
- For steps with an error, the wizard step nav reads "error 1 [step title] error". The first "error" is not translated, and the second one is redundant.
Issue Number: CDE-2292
- For uncompleted steps, the wizard step nav …
> fix(wizard): improve screen reader text for stepnav items

- projects/angular/src/data/datagrid/_datagrid.clarity.scss
Expandable rows first cell with the trigger it's rendered when calculations are happening and it's creating wrong widths for columns.
Issue Number: #1487
That cell is excluded from calculations and they are correct.
> fix(datagrid): remove expand cell from calculations

- projects/angular/src/forms/file-input/file-input.ts
Remove the hidden file `input` element from the tab order because the browse `button` replaces it.
> fix(file-input): remove hidden file `input` from tab order

- projects/angular/clarity.api.md
- projects/angular/src/forms/common/label.spec.ts
- projects/angular/src/forms/common/label.ts
- projects/demo/src/app/forms/layout-angular/layout-angular.html
Currently if you put signposts inside labels they are not working due to that `<label>` be default is spreading a click event to its children and that's causing the signpost to automatically close and not appear.
**Example:**
If you have a label attached to an input or input inside a label and click the label - the input will get focused. 
Issue Number: CDE-9 and #271 
Signposts are now working inside `<label>`.
> fix(label): allow signposts inside labels

- projects/angular/src/forms/file-input/file-input-validator.spec.ts
- projects/angular/src/forms/file-input/file-input-validator.ts
Bugfix
File accept error is set when `accept=""`.
File accept error is not set when `accept=""`.
No.
> fix(file-input): prevent validation error when `accept` is empty string

- projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.spec.ts
- projects/angular/src/data/datagrid/datagrid.spec.ts
- projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
- projects/angular/src/utils/enums/keys.enum.ts
Datagrid key navigation don't work with numpad keys when `NumLock` is off.
Issue Number: CDE-2564
Datagrid key navigation will work with numpad keys when `NumLock` is off.
> fix(datagrid): key navigation when using num pad

- projects/angular/src/data/datagrid/STYLES.md
- projects/angular/src/data/datagrid/_datagrid.clarity.scss
- projects/angular/src/data/datagrid/_properties.datagrid.scss
- projects/angular/src/data/datagrid/_variables.datagrid.scss
Use the same styles as dropdown items for datagrid action items. This results in focus being indicated with an outline instead of focus and hover using the same background color.
CDE-2565
> fix(datagrid): align action items focus/hover/selected with dropdown

- projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
- projects/demo/src/app/datagrid/expandable-rows/expandable-rows.html
When multiple actionable items exist in cell, clicking on any of them, or the cell itself, would forcefully focus the first actionable item.
Issue Number: CDE-2404
Focusing on actionable items in a cell leaves the focus on the clicked item.
Refocusing when clicking on non-actionable content is preserved.
> fix(datagrid): focus handling on actionable element click

- .github/workflows/update-preview-build-branches.yml
- docs/INSTALLATION.md
- scripts/update-preview-build-branches.sh
> chore(ci): add preview build branches

- .github/workflows/update-preview-build-branches.yml
This fixes a mistake I made in #1737 (ae5e764304aa468ca0c8c1ee2ddf9e72e33de916).
> chore(ci): prevent other branches cancelling preview build workflow

- scripts/update-preview-build-branches.sh
I needed to change the local folder and branch name so that it doesn't use slashes because `git worktree add --orphan [branch]` does not work with slashes in the branch name.
> chore(ci): create new preview build branches for workflow dispatch

- projects/demo/src/app/datagrid/preserve-selection/preserve-selection.html
- projects/demo/src/app/datagrid/preserve-selection/preserve-selection.ts
I missed this demo in 8fe236acdd40401d7ecaf0e014587bace1d14fea (#539) and a5694637356de642090ecf5f78bca96372fb8615 (#1144).
> chore(datagrid): make "server-driven, trackBy item" demo work

- .github/workflows/pr-preview.yml
- .github/workflows/release-preview.yml
- .github/workflows/release.yml
This change makes the actions consistent. The secret was already used in the "PR Comment Bot" workflow.
> chore: use `NETLIFY_SITE_NAME` secret instead hard-coding the site name

- projects/angular/src/emphasis/alert/_alert.clarity.scss
The color of the link badge nested in alert is wrong
Issue Number: CDE-2682
Keep the color no matter if it is nested or not.
Tests are added in https://github.com/vmware-clarity/ng-clarity/pull/1771
> fix(badge): nesting inside alert color issue

- tests/screenshot-options.ts
- tests/visual-snapshots.spec.ts
- use `function` for options functions
- add missing parameter type annotations
- rename "screenshot options" constant to camel case per convention
- rename "screenshot options" interface to remove `T` suffix
- rename "screenshot options" interface key with descriptive name
> chore: minor cleanup for visual snapshot screenshot options

- projects/angular/src/data/datagrid/datagrid.ts
Virtual scroll initialize it's subscriptions in datagrid only on change.
Issue Number: CDE-2954
Virtual scroll will initialize it's subscriptions on after view init as well.
> fix(datagrid): virtual scroll subscriptions not initialized on after view init

- .storybook/stories/badge/badge.storybook.component.ts
- projects/angular/clarity.api.md
- projects/angular/src/emphasis/badge/badge.spec.ts
- projects/angular/src/emphasis/badge/badge.ts
- projects/demo/src/app/badges/badge-colors.demo.html
- projects/demo/src/app/badges/badge-statuses.demo.html
Issue Number: CDE-2972, follow up of #2018 
- Property `clrBadgeColor` now is `clrColor`.
- Inner `span` is removed and CSS class are put on `host` level.
> fix(badge): rename color input from `clrBadgeColor` to `clrColor`

- projects/angular/clarity.api.md
- projects/angular/src/data/datagrid/datagrid-page-size.spec.ts
- projects/angular/src/data/datagrid/datagrid-page-size.ts
Page size label gets smacked to the select when datagrid is inside `clrForm`
Issue Number: CDE-2979
Disable grid for page size label
> fix(datagrid): disable grid classes for page size label
